"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import overload
from . import xpu as xpu

class dtype:
    ...


float16: dtype
float32: dtype
bfloat16: dtype
class Size:
    def __getitem__(self, index: int) -> int:
        ...
    
    def __len__(self) -> int:
        ...
    


class Tensor:
    @property
    def shape(self) -> Size:
        ...
    
    def to(self, device: device | str | dtype, **kwargs: object) -> Tensor:
        ...
    
    def clone(self) -> Tensor:
        ...
    
    @overload
    def __getitem__(self, index: int) -> Tensor:
        ...
    
    @overload
    def __getitem__(self, index: slice) -> Tensor:
        ...
    
    @overload
    def __getitem__(self, index: tuple[int | slice, ...]) -> Tensor:
        ...
    
    def item(self) -> int | float:
        ...
    
    def argmax(self, dim: int = ..., keepdim: bool = ...) -> Tensor:
        ...
    
    def __add__(self, other: object) -> Tensor:
        ...
    
    def __truediv__(self, other: object) -> Tensor:
        ...
    
    def __sub__(self, other: object) -> Tensor:
        ...
    
    def __mul__(self, other: object) -> Tensor:
        ...
    


class device:
    type: str
    def __init__(self, device: str | device, index: int | None = ...) -> None:
        ...
    


class no_grad:
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, *args: object) -> None:
        ...
    


def softmax(input: Tensor, dim: int, dtype: dtype | None = ...) -> Tensor:
    ...

def multinomial(input: Tensor, num_samples: int, replacement: bool = ...) -> Tensor:
    ...

def cat(tensors: Sequence[Tensor], dim: int = ...) -> Tensor:
    ...

@overload
def ones(*size: int, device: device | str | None = ..., dtype: dtype | None = ...) -> Tensor:
    ...

@overload
def ones(size: tuple[int, ...], device: device | str | None = ..., dtype: dtype | None = ...) -> Tensor:
    ...

@overload
def zeros(*size: int, device: device | str | None = ..., dtype: dtype | None = ...) -> Tensor:
    ...

@overload
def zeros(size: tuple[int, ...], device: device | str | None = ..., dtype: dtype | None = ...) -> Tensor:
    ...

