include = [ "pyproject.toml", "config.toml", ".taplo.toml", ".github/**/*.toml" ]

[formatting]
align_entries = false
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
compact_arrays = false
compact_inline_tables = false
column_width = 100
indent_tables = false
indent_entries = false
reorder_keys = false
trailing_newline = true
