# Vulture whitelist for Intellicrack false positives.
# Bridge methods dispatched via getattr(), Qt virtual overrides, ctypes _fields_.

intellicrack.__init__.__getattr__  # unused-function
intellicrack.bridges.base.matched_bytes  # unused-variable
intellicrack.bridges.binary.apply_patch  # unused-method
intellicrack.bridges.binary.revert_patch  # unused-method
intellicrack.bridges.binary.search_pattern  # unused-method
intellicrack.bridges.binary.search_pattern_with_wildcards  # unused-method
intellicrack.bridges.binary.disassemble_at_offset  # unused-method
intellicrack.bridges.binary.detail  # unused-attribute
intellicrack.bridges.binary.calculate_checksum  # unused-method
intellicrack.bridges.binary.offset_to_rva  # unused-method
intellicrack.bridges.cutter.get_function  # unused-method
intellicrack.bridges.cutter.search_bytes  # unused-method
intellicrack.bridges.cutter.search_bytes_wildcard  # unused-method
intellicrack.bridges.cutter.rename_function  # unused-method
intellicrack.bridges.cutter.add_comment  # unused-method
intellicrack.bridges.cutter.assemble_at  # unused-method
intellicrack.bridges.cutter.seek  # unused-method
intellicrack.bridges.cutter.get_function_address  # unused-method
intellicrack.bridges.frida_bridge.enumerate_modules  # unused-method
intellicrack.bridges.frida_bridge.enumerate_exports  # unused-method
intellicrack.bridges.frida_bridge.get_hooks  # unused-method
intellicrack.bridges.frida_bridge.execute_script  # unused-method
intellicrack.bridges.frida_bridge.intercept_return  # unused-method
intellicrack.bridges.frida_bridge.call_function  # unused-method
intellicrack.bridges.frida_bridge.allocate_memory  # unused-method
intellicrack.bridges.frida_bridge.protect_memory  # unused-method
intellicrack.bridges.frida_bridge.find_base_address  # unused-method
intellicrack.bridges.frida_bridge.resolve_symbol  # unused-method
intellicrack.bridges.frida_bridge.find_functions_named  # unused-method
intellicrack.bridges.frida_bridge.resolve_api  # unused-method
intellicrack.bridges.frida_bridge.replace_function  # unused-method
intellicrack.bridges.frida_bridge.enable_child_gating  # unused-method
intellicrack.bridges.frida_bridge.disable_child_gating  # unused-method
intellicrack.bridges.frida_bridge.get_pending_children  # unused-method
intellicrack.bridges.frida_bridge.resume_child  # unused-method
intellicrack.bridges.frida_bridge.enable_crash_reporting  # unused-method
intellicrack.bridges.frida_bridge.get_crashes  # unused-method
intellicrack.bridges.ghidra.get_function  # unused-method
intellicrack.bridges.ghidra.search_bytes  # unused-method
intellicrack.bridges.ghidra.rename_function  # unused-method
intellicrack.bridges.ghidra.add_comment  # unused-method
intellicrack.bridges.ghidra.get_data_type  # unused-method
intellicrack.bridges.ghidra.set_data_type  # unused-method
intellicrack.bridges.ghidra.execute_script  # unused-method
intellicrack.bridges.ghidra.set_label  # unused-method
intellicrack.bridges.ghidra.get_labels  # unused-method
intellicrack.bridges.ghidra.create_bookmark  # unused-method
intellicrack.bridges.ghidra.get_bookmarks  # unused-method
intellicrack.bridges.ghidra.create_function  # unused-method
intellicrack.bridges.ghidra.delete_function  # unused-method
intellicrack.bridges.ghidra.edit_function_signature  # unused-method
intellicrack.bridges.ghidra.set_function_variable_type  # unused-method
intellicrack.bridges.ghidra.define_structure  # unused-method
intellicrack.bridges.ghidra.get_structures  # unused-method
intellicrack.bridges.ghidra.apply_structure_at  # unused-method
intellicrack.bridges.ghidra.get_call_graph  # unused-method
intellicrack.bridges.ghidra.get_segments  # unused-method
intellicrack.bridges.ghidra.get_program_info  # unused-method
intellicrack.bridges.hex_editor.open_file  # unused-method
intellicrack.bridges.hex_editor.close_file  # unused-method
intellicrack.bridges.hex_editor.get_cursor_position  # unused-method
intellicrack.bridges.hex_editor.select_range  # unused-method
intellicrack.bridges.hex_editor.get_selection  # unused-method
intellicrack.bridges.hex_editor.inspect_data_at  # unused-method
intellicrack.bridges.hex_editor.calculate_hash  # unused-method
intellicrack.bridges.hex_editor.get_byte_statistics  # unused-method
intellicrack.bridges.hex_editor.register_template  # unused-method
intellicrack.bridges.hex_editor.compile_pattern  # unused-method
intellicrack.bridges.hex_editor.execute_pattern  # unused-method
intellicrack.bridges.hex_editor.execute_pattern_file  # unused-method
intellicrack.bridges.hex_editor.list_hexpat_patterns  # unused-method
intellicrack.bridges.hex_editor.auto_detect_pattern  # unused-method
intellicrack.bridges.hex_editor.export_template  # unused-method
intellicrack.bridges.hex_editor.compare_files  # unused-method
intellicrack.bridges.hex_editor.save_as  # unused-method
intellicrack.bridges.hex_editor.calculate_hash_range  # unused-method
intellicrack.bridges.hex_editor.get_context_for_ai  # unused-method
intellicrack.bridges.hex_editor.get_entropy_map  # unused-method
intellicrack.bridges.hex_editor.get_byte_distribution  # unused-method
intellicrack.bridges.hex_editor.get_byte_type_distribution  # unused-method
intellicrack.bridges.hex_editor.get_digram_matrix  # unused-method
intellicrack.bridges.hex_editor.get_content_classification  # unused-method
intellicrack.bridges.hex_editor.yara_scan  # unused-method
intellicrack.bridges.hex_editor.yara_scan_files  # unused-method
intellicrack.bridges.hex_editor.apply_transform  # unused-method
intellicrack.bridges.hex_editor.apply_pipeline  # unused-method
intellicrack.bridges.hex_editor.calculate_hash_custom_crc  # unused-method
intellicrack.bridges.hex_editor.export_patches  # unused-method
intellicrack.bridges.hex_editor.import_patches  # unused-method
intellicrack.bridges.hex_editor.add_highlight_rule  # unused-method
intellicrack.bridges.hex_editor.remove_highlight_rule  # unused-method
intellicrack.bridges.hex_editor.list_highlight_rules  # unused-method
intellicrack.bridges.hex_state.clear_selection  # unused-method
intellicrack.bridges.process.open_process  # unused-method
intellicrack.bridges.process.suspend  # unused-method
intellicrack.bridges.process.protect  # unused-method
intellicrack.bridges.process.search_pattern  # unused-method
intellicrack.bridges.process.inject_dll  # unused-method
intellicrack.bridges.process.get_process_info  # unused-method
intellicrack.bridges.sandbox_bridge.copy_to  # unused-method
intellicrack.bridges.sandbox_bridge.copy_from  # unused-method
intellicrack.bridges.sandbox_bridge.snapshot_create  # unused-method
intellicrack.bridges.sandbox_bridge.snapshot_restore  # unused-method
intellicrack.bridges.sandbox_bridge.snapshot_list  # unused-method
intellicrack.bridges.sandbox_bridge.snapshot_delete  # unused-method
intellicrack.bridges.schemas.input_schema  # unused-variable
intellicrack.bridges.x64dbg.WIN_PAGE_EXECUTE_READWRITE  # unused-variable
intellicrack.bridges.x64dbg.MAX_LOCAL_VARS  # unused-variable
intellicrack.bridges.x64dbg.dwFlags  # unused-attribute
intellicrack.bridges.x64dbg.wShowWindow  # unused-attribute
intellicrack.bridges.x64dbg.set_watchpoint  # unused-method
intellicrack.bridges.x64dbg.remove_watchpoint  # unused-method
intellicrack.bridges.x64dbg.get_watchpoints  # unused-method
intellicrack.bridges.x64dbg.allocate_memory  # unused-method
intellicrack.bridges.x64dbg.free_memory  # unused-method
intellicrack.bridges.x64dbg.assemble_at  # unused-method
intellicrack.bridges.x64dbg.get_process_info  # unused-method
intellicrack.bridges.x64dbg.find_pattern  # unused-method
intellicrack.bridges.x64dbg.run_to  # unused-method
intellicrack.bridges.x64dbg.execute_til_return  # unused-method
intellicrack.bridges.x64dbg.skip_instruction  # unused-method
intellicrack.bridges.x64dbg.set_ip  # unused-method
intellicrack.bridges.x64dbg.set_label  # unused-method
intellicrack.bridges.x64dbg.get_labels  # unused-method
intellicrack.bridges.x64dbg.set_comment  # unused-method
intellicrack.bridges.x64dbg.get_comments  # unused-method
intellicrack.bridges.x64dbg.enable_breakpoint  # unused-method
intellicrack.bridges.x64dbg.disable_breakpoint  # unused-method
intellicrack.bridges.x64dbg.set_breakpoint_on_api  # unused-method
intellicrack.bridges.x64dbg.dump_memory_to_file  # unused-method
intellicrack.bridges.x64dbg.get_module_sections  # unused-method
intellicrack.bridges.x64dbg.get_module_exports  # unused-method
intellicrack.bridges.x64dbg.trace_start  # unused-method
intellicrack.bridges.x64dbg.trace_stop  # unused-method
intellicrack.bridges.x64dbg.set_exception_config  # unused-method
intellicrack.core.disassembler.detail  # unused-attribute
intellicrack.core.hexpat.ast_nodes.is_const  # unused-variable
intellicrack.core.hexpat.interpreter.execute_bytes  # unused-method
intellicrack.core.hexpat.pattern_registry.get_pattern  # unused-method
intellicrack.core.hexpat.stdlib.set_array_index  # unused-method
intellicrack.core.logging.get_structlog_logger  # unused-function
intellicrack.core.process_manager.ASYNC_SUBPROCESS  # unused-variable
intellicrack.core.session.row_factory  # unused-attribute
intellicrack.core.template_manager._config_dir  # unused-attribute
intellicrack.core.template_manager.bootstrap_builtins  # unused-method
intellicrack.core.template_manager.list_all_templates  # unused-method
intellicrack.core.template_manager.save_user_template  # unused-method
intellicrack.core.template_manager.delete_user_template  # unused-method
intellicrack.core.template_manager.list_hexpat_patterns  # unused-method
intellicrack.core.template_manager.list_hexpat_by_category  # unused-method
intellicrack.core.tools.get_process_bridge  # unused-method
intellicrack.core.tools.get_sandbox_bridge  # unused-method
intellicrack.core.types.thinking_content  # unused-variable
intellicrack.core.types.rflags  # unused-variable
intellicrack.core.yara_scanner.scan_data_async  # unused-method
intellicrack.core.yara_scanner.scan_file_async  # unused-method
intellicrack.credentials.oauth.log_request  # unused-method
intellicrack.credentials.oauth.authorize_google  # unused-function
intellicrack.providers.anthropic._credentials  # unused-attribute
intellicrack.providers.base.input_schema  # unused-variable
intellicrack.providers.base._credentials  # unused-attribute
intellicrack.providers.base._credentials  # unused-attribute
intellicrack.providers.google._credentials  # unused-attribute
intellicrack.providers.grok.tool_call_id  # unused-variable
intellicrack.providers.grok._credentials  # unused-attribute
intellicrack.providers.huggingface._credentials  # unused-attribute
intellicrack.providers.local_transformers._credentials  # unused-attribute
intellicrack.providers.ollama._credentials  # unused-attribute
intellicrack.providers.openai.tool_call_id  # unused-variable
intellicrack.providers.openai._credentials  # unused-attribute
intellicrack.providers.openrouter._credentials  # unused-attribute
intellicrack.providers.registry.get_active_or_raise  # unused-method
intellicrack.sandbox.base.value_name  # unused-variable
intellicrack.sandbox.base.value_data  # unused-variable
intellicrack.sandbox.base.local_address  # unused-variable
intellicrack.sandbox.base.local_port  # unused-variable
intellicrack.sandbox.base.remote_address  # unused-variable
intellicrack.sandbox.base.remote_port  # unused-variable
intellicrack.sandbox.base.bytes_sent  # unused-variable
intellicrack.sandbox.base.bytes_received  # unused-variable
intellicrack.sandbox.base.get_status_info  # unused-method
intellicrack.ui.app._model_browse_worker  # unused-attribute
intellicrack.ui.app._script_validator  # unused-attribute
intellicrack.ui.app._script_validator  # unused-attribute
intellicrack.ui.app._model_browse_worker  # unused-attribute
intellicrack.ui.panels.cutter_panel._asm_highlighter  # unused-attribute
intellicrack.ui.panels.cutter_panel._c_highlighter  # unused-attribute
intellicrack.ui.panels.hex_editor._base.hex_state_available  # unused-variable
intellicrack.ui.panels.hex_editor._base.hex_state_available  # unused-variable
intellicrack.ui.panels.hex_editor._base.transform_pipeline_available  # unused-variable
intellicrack.ui.panels.hex_editor._base.transform_pipeline_available  # unused-variable
intellicrack.ui.panels.hex_editor._bookmarks._on_bookmark_double_clicked  # unused-method
intellicrack.ui.panels.hex_editor._statistics.classification_block_size  # unused-variable
intellicrack.ui.panels.hex_editor_widget.DISPLAY_MODES  # unused-variable
intellicrack.ui.panels.hex_editor_widget.DISPLAY_MODES  # unused-variable
intellicrack.ui.panels.hex_editor_widget.add_highlight_rule  # unused-method
intellicrack.ui.panels.hex_editor_widget.remove_highlight_rule  # unused-method
intellicrack.ui.panels.qt_compat.edit_table_item  # unused-function
intellicrack.ui.panels.stack_viewer.set_data_source  # unused-method
intellicrack.ui.resources.icon_manager.icon_exists  # unused-method
intellicrack.ui.tools.get_highlighter  # unused-method
intellicrack.ui.tools._ghidra_bridge  # unused-attribute
intellicrack.ui.tools._cutter_bridge  # unused-attribute
intellicrack.ui.tools._cutter_bridge  # unused-attribute
intellicrack.ui.tools._ghidra_bridge  # unused-attribute
