import enum
import typing

import PyQt6.sip

class pyqtSignal:
    signatures: tuple[str, ...]
    def __init__(self, *types: type, name: str = ...) -> None: ...
    @typing.overload
    def __get__(self, instance: None, owner: type[QObject]) -> pyqtSignal: ...
    @typing.overload
    def __get__(self, instance: QObject, owner: type[QObject]) -> pyqtBoundSignal: ...

class pyqtBoundSignal:
    signal: str
    def __getitem__(self, key: object) -> pyqtBoundSignal: ...
    def connect(self, slot: typing.Callable[..., object] | pyqtBoundSignal) -> QMetaObject.Connection: ...
    @typing.overload
    def disconnect(self) -> None: ...
    @typing.overload
    def disconnect(
        self, slot: typing.Callable[..., object] | pyqtBoundSignal | QMetaObject.Connection
    ) -> None: ...
    def emit(self, *args: object) -> None: ...

PYQT_SIGNAL = pyqtSignal | pyqtBoundSignal
PYQT_SLOT = typing.Callable[..., object] | pyqtBoundSignal

_FuncT = typing.TypeVar("_FuncT", bound=typing.Callable[..., object])

def pyqtSlot(*types: type, name: str | None = ..., result: type | None = ...) -> typing.Callable[[_FuncT], _FuncT]: ...

QObjectT = typing.TypeVar("QObjectT", bound="QObject")

class QObject:
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def objectName(self) -> str: ...
    def setObjectName(self, name: str) -> None: ...
    def parent(self) -> QObject | None: ...
    def setParent(self, parent: QObject | None) -> None: ...
    def children(self) -> list[QObject]: ...
    @typing.overload
    def findChild(self, type: type[QObjectT], name: str = ..., options: Qt.FindChildOption = ...) -> QObjectT | None: ...
    @typing.overload
    def findChild(self, types: tuple[type[QObjectT], ...], name: str = ..., options: Qt.FindChildOption = ...) -> QObjectT | None: ...
    @typing.overload
    def findChildren(self, type: type[QObjectT], name: str = ..., options: Qt.FindChildOption = ...) -> list[QObjectT]: ...
    @typing.overload
    def findChildren(self, types: tuple[type[QObjectT], ...], name: str = ..., options: Qt.FindChildOption = ...) -> list[QObjectT]: ...
    def deleteLater(self) -> None: ...
    def blockSignals(self, block: bool) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def property(self, name: str) -> typing.Any: ...
    def setProperty(self, name: str, value: typing.Any) -> bool: ...
    def inherits(self, classname: str) -> bool: ...
    def thread(self) -> QThread | None: ...
    def moveToThread(self, thread: QThread | None) -> None: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def sender(self) -> QObject | None: ...
    destroyed: typing.ClassVar[pyqtSignal]
    objectNameChanged: typing.ClassVar[pyqtSignal]

class QMetaObject:
    class Connection:
        def __init__(self) -> None: ...
        def __bool__(self) -> bool: ...

class QThread(QObject):
    started: typing.ClassVar[pyqtSignal]
    finished: typing.ClassVar[pyqtSignal]
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def run(self) -> None: ...
    def start(self, priority: QThread.Priority = ...) -> None: ...
    def terminate(self) -> None: ...
    def quit(self) -> None: ...
    @typing.overload
    def wait(self, time: int = ...) -> bool: ...
    @typing.overload
    def wait(self, deadline: QDeadlineTimer) -> bool: ...
    def isRunning(self) -> bool: ...
    def isFinished(self) -> bool: ...
    def requestInterruption(self) -> None: ...
    def isInterruptionRequested(self) -> bool: ...
    @staticmethod
    def currentThread() -> QThread: ...
    @staticmethod
    def msleep(msecs: int) -> None: ...
    @staticmethod
    def sleep(secs: int) -> None: ...
    @staticmethod
    def usleep(usecs: int) -> None: ...
    class Priority(enum.Enum):
        IdlePriority = ...
        LowestPriority = ...
        LowPriority = ...
        NormalPriority = ...
        HighPriority = ...
        HighestPriority = ...
        TimeCriticalPriority = ...
        InheritPriority = ...

class QDeadlineTimer:
    def __init__(self, msecs: int = ...) -> None: ...

class QTimer(QObject):
    timeout: typing.ClassVar[pyqtSignal]
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def start(self, msec: int = ...) -> None: ...
    def stop(self) -> None: ...
    def isActive(self) -> bool: ...
    def setInterval(self, msec: int) -> None: ...
    def interval(self) -> int: ...
    def setSingleShot(self, singleShot: bool) -> None: ...
    def isSingleShot(self) -> bool: ...
    def remainingTime(self) -> int: ...
    @typing.overload
    @staticmethod
    def singleShot(msec: int, slot: typing.Callable[..., typing.Any]) -> None: ...
    @typing.overload
    @staticmethod
    def singleShot(msec: int, timerType: Qt.TimerType, slot: typing.Callable[..., typing.Any]) -> None: ...

class QEvent:
    class Type(enum.Enum): ...

    def __init__(self, type: QEvent.Type) -> None: ...
    def type(self) -> QEvent.Type: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...
    def isAccepted(self) -> bool: ...
    def setAccepted(self, accepted: bool) -> None: ...

class QTimerEvent(QEvent):
    def __init__(self, timerId: int) -> None: ...
    def timerId(self) -> int: ...

class Qt:
    class ToolBarArea(enum.Flag):
        LeftToolBarArea = ...
        RightToolBarArea = ...
        TopToolBarArea = ...
        BottomToolBarArea = ...
        AllToolBarAreas = ...
        NoToolBarArea = ...

    class Orientation(enum.Enum):
        Horizontal = ...
        Vertical = ...

    class AlignmentFlag(enum.Flag):
        AlignLeft = ...
        AlignRight = ...
        AlignHCenter = ...
        AlignTop = ...
        AlignBottom = ...
        AlignVCenter = ...
        AlignCenter = ...

    class WindowType(enum.Flag):
        Widget = ...
        Window = ...
        Dialog = ...
        Sheet = ...
        Drawer = ...
        Popup = ...
        Tool = ...
        ToolTip = ...
        SplashScreen = ...
        SubWindow = ...
        WindowStaysOnTopHint = ...
        FramelessWindowHint = ...

    class ItemDataRole(enum.Enum):
        DisplayRole = ...
        EditRole = ...
        UserRole = ...
        DecorationRole = ...
        ToolTipRole = ...
        StatusTipRole = ...
        WhatsThisRole = ...
        FontRole = ...
        TextAlignmentRole = ...
        BackgroundRole = ...
        ForegroundRole = ...
        CheckStateRole = ...

    class ItemFlag(enum.Flag):
        NoItemFlags = ...
        ItemIsSelectable = ...
        ItemIsEditable = ...
        ItemIsDragEnabled = ...
        ItemIsDropEnabled = ...
        ItemIsUserCheckable = ...
        ItemIsEnabled = ...

    class CheckState(enum.Enum):
        Unchecked = ...
        PartiallyChecked = ...
        Checked = ...

    class TextInteractionFlag(enum.Flag):
        NoTextInteraction = ...
        TextSelectableByMouse = ...
        TextSelectableByKeyboard = ...
        LinksAccessibleByMouse = ...
        LinksAccessibleByKeyboard = ...
        TextEditable = ...
        TextEditorInteraction = ...
        TextBrowserInteraction = ...

    class WindowModality(enum.Enum):
        NonModal = ...
        WindowModal = ...
        ApplicationModal = ...

    class FocusPolicy(enum.Enum):
        NoFocus = ...
        TabFocus = ...
        ClickFocus = ...
        StrongFocus = ...
        WheelFocus = ...

    class ScrollBarPolicy(enum.Enum):
        ScrollBarAsNeeded = ...
        ScrollBarAlwaysOff = ...
        ScrollBarAlwaysOn = ...

    class ContextMenuPolicy(enum.Enum):
        NoContextMenu = ...
        DefaultContextMenu = ...
        ActionsContextMenu = ...
        CustomContextMenu = ...
        PreventContextMenu = ...

    class CursorShape(enum.Enum):
        ArrowCursor = ...
        UpArrowCursor = ...
        CrossCursor = ...
        WaitCursor = ...
        IBeamCursor = ...
        PointingHandCursor = ...

    class ConnectionType(enum.Enum):
        AutoConnection = ...
        DirectConnection = ...
        QueuedConnection = ...
        BlockingQueuedConnection = ...
        UniqueConnection = ...

    class FindChildOption(enum.Flag):
        FindDirectChildrenOnly = ...
        FindChildrenRecursively = ...

    class ToolButtonStyle(enum.Enum):
        ToolButtonIconOnly = ...
        ToolButtonTextOnly = ...
        ToolButtonTextBesideIcon = ...
        ToolButtonTextUnderIcon = ...
        ToolButtonFollowStyle = ...

    class DockWidgetArea(enum.Flag):
        LeftDockWidgetArea = ...
        RightDockWidgetArea = ...
        TopDockWidgetArea = ...
        BottomDockWidgetArea = ...
        AllDockWidgetAreas = ...
        NoDockWidgetArea = ...

    class Corner(enum.Enum):
        TopLeftCorner = ...
        TopRightCorner = ...
        BottomLeftCorner = ...
        BottomRightCorner = ...

    class TimerType(enum.Enum):
        PreciseTimer = ...
        CoarseTimer = ...
        VeryCoarseTimer = ...

    class AspectRatioMode(enum.Enum):
        IgnoreAspectRatio = ...
        KeepAspectRatio = ...
        KeepAspectRatioByExpanding = ...

    class TransformationMode(enum.Enum):
        FastTransformation = ...
        SmoothTransformation = ...

    class TextFormat(enum.Enum):
        PlainText = ...
        RichText = ...
        AutoText = ...
        MarkdownText = ...

    class GlobalColor(enum.Enum):
        color0 = ...
        color1 = ...
        black = ...
        white = ...
        darkGray = ...
        gray = ...
        lightGray = ...
        red = ...
        green = ...
        blue = ...
        cyan = ...
        magenta = ...
        yellow = ...
        darkRed = ...
        darkGreen = ...
        darkBlue = ...
        darkCyan = ...
        darkMagenta = ...
        darkYellow = ...
        transparent = ...

    class MatchFlag(enum.Flag):
        MatchExactly = ...
        MatchContains = ...
        MatchStartsWith = ...
        MatchEndsWith = ...
        MatchRegularExpression = ...
        MatchWildcard = ...
        MatchCaseSensitive = ...
        MatchWrap = ...
        MatchRecursive = ...

class QSize:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, width: int, height: int) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def expandedTo(self, other: QSize) -> QSize: ...
    def boundedTo(self, other: QSize) -> QSize: ...

class QPoint:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, x: int, y: int) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def isNull(self) -> bool: ...

class QRect:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, topLeft: QPoint, bottomRight: QPoint) -> None: ...
    @typing.overload
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def left(self) -> int: ...
    def right(self) -> int: ...
    def top(self) -> int: ...
    def bottom(self) -> int: ...
    def topLeft(self) -> QPoint: ...
    def topRight(self) -> QPoint: ...
    def bottomLeft(self) -> QPoint: ...
    def bottomRight(self) -> QPoint: ...
    def center(self) -> QPoint: ...
    def size(self) -> QSize: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def setLeft(self, x: int) -> None: ...
    def setRight(self, x: int) -> None: ...
    def setTop(self, y: int) -> None: ...
    def setBottom(self, y: int) -> None: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def contains(self, *args: typing.Any) -> bool: ...
    def intersects(self, rect: QRect) -> bool: ...

class QMargins:
    def __init__(self, left: int = 0, top: int = 0, right: int = 0, bottom: int = 0) -> None: ...
    def left(self) -> int: ...
    def top(self) -> int: ...
    def right(self) -> int: ...
    def bottom(self) -> int: ...

class QModelIndex:
    def __init__(self) -> None: ...
    def row(self) -> int: ...
    def column(self) -> int: ...
    def parent(self) -> QModelIndex: ...
    def sibling(self, row: int, column: int) -> QModelIndex: ...
    def data(self, role: int | Qt.ItemDataRole = ...) -> typing.Any: ...
    def flags(self) -> Qt.ItemFlag: ...
    def model(self) -> typing.Any: ...
    def isValid(self) -> bool: ...

class QUrl:
    def __init__(self, url: str = ...) -> None: ...
    def toString(self) -> str: ...
    def toLocalFile(self) -> str: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def scheme(self) -> str: ...
    def host(self) -> str: ...
    def port(self, defaultPort: int = ...) -> int: ...
    def path(self) -> str: ...
    @staticmethod
    def fromLocalFile(localFile: str) -> QUrl: ...

class QByteArray(PyQt6.sip.simplewrapper):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, data: bytes) -> None: ...
    @typing.overload
    def __init__(self, a: QByteArray | bytes | bytearray | memoryview) -> None: ...
    def data(self) -> bytes: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def clear(self) -> None: ...

class QRegularExpressionMatch:
    def hasMatch(self) -> bool: ...
    def hasPartialMatch(self) -> bool: ...
    def captured(self, nth: int = ...) -> str: ...
    def capturedStart(self, nth: int = ...) -> int: ...
    def capturedEnd(self, nth: int = ...) -> int: ...
    def capturedLength(self, nth: int = ...) -> int: ...
    def capturedTexts(self) -> list[str]: ...
    def lastCapturedIndex(self) -> int: ...
    def regularExpression(self) -> QRegularExpression: ...

class QRegularExpressionMatchIterator:
    def hasNext(self) -> bool: ...
    def next(self) -> QRegularExpressionMatch: ...
    def peekNext(self) -> QRegularExpressionMatch: ...
    def regularExpression(self) -> QRegularExpression: ...
    def isValid(self) -> bool: ...

class QRegularExpression:
    class PatternOption(enum.Flag):
        NoPatternOption = ...
        CaseInsensitiveOption = ...
        DotMatchesEverythingOption = ...
        MultilineOption = ...

    def __init__(self, pattern: str = ..., options: QRegularExpression.PatternOption = ...) -> None: ...
    def pattern(self) -> str: ...
    def setPattern(self, pattern: str) -> None: ...
    def isValid(self) -> bool: ...
    def match(self, subject: str, offset: int = ..., matchType: int = ..., matchOptions: int = ...) -> QRegularExpressionMatch: ...
    def globalMatch(self, subject: str, offset: int = ..., matchType: int = ..., matchOptions: int = ...) -> QRegularExpressionMatchIterator: ...

class QSettings:
    def __init__(self, *args: typing.Any) -> None: ...
    def value(self, key: str, defaultValue: typing.Any = ...) -> typing.Any: ...
    def setValue(self, key: str, value: typing.Any) -> None: ...
    def contains(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def clear(self) -> None: ...
    def sync(self) -> None: ...
    def allKeys(self) -> list[str]: ...

class QMutex:
    def __init__(self) -> None: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def tryLock(self, timeout: int = ...) -> bool: ...
