import enum
import typing

from PyQt6 import QtCore

class QColor:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, r: int, g: int, b: int, a: int = ...) -> None: ...
    @typing.overload
    def __init__(self, name: str) -> None: ...
    @typing.overload
    def __init__(self, color: int) -> None: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...
    def alpha(self) -> int: ...
    def setRed(self, red: int) -> None: ...
    def setGreen(self, green: int) -> None: ...
    def setBlue(self, blue: int) -> None: ...
    def setAlpha(self, alpha: int) -> None: ...
    def name(self) -> str: ...
    def isValid(self) -> bool: ...
    def lighter(self, factor: int = ...) -> QColor: ...
    def darker(self, factor: int = ...) -> QColor: ...

class QFont:
    class Weight(enum.Enum):
        Thin = ...
        ExtraLight = ...
        Light = ...
        Normal = ...
        Medium = ...
        DemiBold = ...
        Bold = ...
        ExtraBold = ...
        Black = ...

    class StyleHint(enum.Enum):
        Helvetica = ...
        SansSerif = ...
        Times = ...
        Serif = ...
        Courier = ...
        TypeWriter = ...
        OldEnglish = ...
        Decorative = ...
        System = ...
        AnyStyle = ...
        Cursive = ...
        Monospace = ...
        Fantasy = ...

    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, family: str, pointSize: int = ..., weight: typing.Union[int, QFont.Weight] = ..., italic: bool = ...) -> None: ...
    @typing.overload
    def __init__(self, families: typing.Sequence[str], pointSize: int = ..., weight: typing.Union[int, QFont.Weight] = ..., italic: bool = ...) -> None: ...
    def family(self) -> str: ...
    def setFamily(self, family: str) -> None: ...
    def families(self) -> list[str]: ...
    def setFamilies(self, families: typing.Sequence[str]) -> None: ...
    def pointSize(self) -> int: ...
    def setPointSize(self, size: int) -> None: ...
    def pixelSize(self) -> int: ...
    def setPixelSize(self, size: int) -> None: ...
    def weight(self) -> QFont.Weight: ...
    def setWeight(self, weight: QFont.Weight) -> None: ...
    def bold(self) -> bool: ...
    def setBold(self, enable: bool) -> None: ...
    def italic(self) -> bool: ...
    def setItalic(self, enable: bool) -> None: ...
    def underline(self) -> bool: ...
    def setUnderline(self, enable: bool) -> None: ...
    def strikeOut(self) -> bool: ...
    def setStrikeOut(self, enable: bool) -> None: ...
    def fixedPitch(self) -> bool: ...
    def setFixedPitch(self, enable: bool) -> None: ...
    def styleHint(self) -> QFont.StyleHint: ...
    def setStyleHint(self, hint: QFont.StyleHint) -> None: ...

class QTextCharFormat:
    def __init__(self) -> None: ...
    def setForeground(self, brush: typing.Union[QColor, QBrush]) -> None: ...
    def foreground(self) -> QBrush: ...
    def setBackground(self, brush: typing.Union[QColor, QBrush]) -> None: ...
    def background(self) -> QBrush: ...
    def setFont(self, font: QFont) -> None: ...
    def font(self) -> QFont: ...
    def setFontWeight(self, weight: int | QFont.Weight) -> None: ...
    def fontWeight(self) -> int: ...
    def setFontItalic(self, italic: bool) -> None: ...
    def fontItalic(self) -> bool: ...
    def setFontUnderline(self, underline: bool) -> None: ...
    def fontUnderline(self) -> bool: ...
    def setFontFamily(self, family: str) -> None: ...
    def fontFamily(self) -> str: ...
    def setFontPointSize(self, size: float) -> None: ...
    def fontPointSize(self) -> float: ...

class QTextDocument(QtCore.QObject):
    def __init__(self, parent: QtCore.QObject | None = ...) -> None: ...
    def toPlainText(self) -> str: ...
    def toHtml(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...
    def setHtml(self, html: str) -> None: ...
    def isEmpty(self) -> bool: ...
    def characterCount(self) -> int: ...
    def lineCount(self) -> int: ...
    def blockCount(self) -> int: ...
    def clear(self) -> None: ...
    def defaultFont(self) -> QFont: ...
    def setDefaultFont(self, font: QFont) -> None: ...
    def findBlockByLineNumber(self, line: int) -> QTextBlock: ...

class QSyntaxHighlighter(QtCore.QObject):
    def __init__(self, parent: typing.Union[QTextDocument, None] = ...) -> None: ...
    def document(self) -> typing.Union[QTextDocument, None]: ...
    def setDocument(self, doc: typing.Union[QTextDocument, None]) -> None: ...
    def rehighlight(self) -> None: ...
    def highlightBlock(self, text: str) -> None: ...
    def setFormat(self, start: int, count: int, format: typing.Union[QTextCharFormat, QColor, QFont]) -> None: ...
    def format(self, position: int) -> QTextCharFormat: ...
    def currentBlockState(self) -> int: ...
    def previousBlockState(self) -> int: ...
    def setCurrentBlockState(self, state: int) -> None: ...

class QTextCursor:
    class MoveOperation(enum.Enum):
        Start = ...
        End = ...
        Up = ...
        Down = ...
        Left = ...
        Right = ...

    def __init__(self, *args: typing.Any) -> None: ...
    def moveCursor(self, operation: QTextCursor.MoveOperation, mode: int = ...) -> bool: ...
    def position(self) -> int: ...
    def setPosition(self, pos: int, mode: int = ...) -> None: ...
    def select(self, selection: int) -> None: ...
    def selectedText(self) -> str: ...
    def hasSelection(self) -> bool: ...
    def clearSelection(self) -> None: ...
    def insertText(self, text: str) -> None: ...

class QTextBlock:
    def isValid(self) -> bool: ...
    def text(self) -> str: ...
    def blockNumber(self) -> int: ...
    def document(self) -> QTextDocument | None: ...
    def setDocument(self, doc: QTextDocument | None) -> None: ...
    def rehighlight(self) -> None: ...
    def highlightBlock(self, text: str) -> None: ...
    def setFormat(self, start: int, count: int, format: QTextCharFormat) -> None: ...
    def format(self, position: int) -> QTextCharFormat: ...
    def currentBlock(self) -> typing.Any: ...
    def currentBlockState(self) -> int: ...
    def previousBlockState(self) -> int: ...
    def setCurrentBlockState(self, state: int) -> None: ...

class QIcon:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, pixmap: QPixmap) -> None: ...
    @typing.overload
    def __init__(self, fileName: str) -> None: ...
    @typing.overload
    def __init__(self, other: QIcon) -> None: ...
    def isNull(self) -> bool: ...
    def addFile(self, fileName: str, size: QtCore.QSize = ..., mode: QIcon.Mode = ..., state: QIcon.State = ...) -> None: ...
    def addPixmap(self, pixmap: QPixmap, mode: QIcon.Mode = ..., state: QIcon.State = ...) -> None: ...
    def pixmap(self, *args: typing.Any) -> QPixmap: ...
    @staticmethod
    def fromTheme(name: str) -> QIcon: ...
    class Mode(enum.Enum):
        Normal = ...
        Disabled = ...
        Active = ...
        Selected = ...

    class State(enum.Enum):
        On = ...
        Off = ...

class QPixmap:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, width: int, height: int) -> None: ...
    @typing.overload
    def __init__(self, fileName: str, format: str | None = ...) -> None: ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QtCore.QSize: ...
    def rect(self) -> QtCore.QRect: ...
    def scaled(self, *args: typing.Any) -> QPixmap: ...
    def fill(self, color: QColor = ...) -> None: ...
    def save(self, fileName: str, format: str | None = ..., quality: int = ...) -> bool: ...
    def load(self, fileName: str, format: str | None = ...) -> bool: ...

class QImage:
    def __init__(self, *args: typing.Any) -> None: ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QtCore.QSize: ...
    def save(self, fileName: str, format: str | None = ..., quality: int = ...) -> bool: ...
    def load(self, fileName: str, format: str | None = ...) -> bool: ...

class QPainter:
    class RenderHint(enum.Flag):
        Antialiasing = ...
        TextAntialiasing = ...
        SmoothPixmapTransform = ...
        VerticalSubpixelPositioning = ...
        LosslessImageRendering = ...
        NonCosmeticBrushPatterns = ...

    def __init__(self, device: typing.Any = ...) -> None: ...
    def begin(self, device: typing.Any) -> bool: ...
    def end(self) -> bool: ...
    def drawText(self, *args: typing.Any) -> None: ...
    def drawRect(self, *args: typing.Any) -> None: ...
    def fillRect(self, *args: typing.Any) -> None: ...
    def setPen(self, pen: typing.Any) -> None: ...
    def setFont(self, font: QFont) -> None: ...
    def font(self) -> QFont: ...
    def save(self) -> None: ...
    def restore(self) -> None: ...
    def setRenderHint(self, hint: QPainter.RenderHint, on: bool = ...) -> None: ...
    def setRenderHints(self, hints: QPainter.RenderHint, on: bool = ...) -> None: ...

class QPen:
    def __init__(self, *args: typing.Any) -> None: ...
    def setColor(self, color: QColor) -> None: ...
    def color(self) -> QColor: ...
    def setWidth(self, width: int) -> None: ...
    def width(self) -> int: ...

class QBrush:
    def __init__(self, *args: typing.Any) -> None: ...
    def setColor(self, color: QColor) -> None: ...
    def color(self) -> QColor: ...

class QPalette:
    class ColorRole(enum.Enum):
        Window = ...
        WindowText = ...
        Base = ...
        AlternateBase = ...
        ToolTipBase = ...
        ToolTipText = ...
        PlaceholderText = ...
        Text = ...
        Button = ...
        ButtonText = ...
        BrightText = ...
        Light = ...
        Midlight = ...
        Dark = ...
        Mid = ...
        Shadow = ...
        Highlight = ...
        HighlightedText = ...
        Link = ...
        LinkVisited = ...

    def __init__(self, *args: typing.Any) -> None: ...
    def setColor(self, role: QPalette.ColorRole, color: QColor) -> None: ...
    def color(self, role: QPalette.ColorRole) -> QColor: ...

class QCursor:
    def __init__(self, shape: QtCore.Qt.CursorShape = ...) -> None: ...
    @staticmethod
    def pos() -> QtCore.QPoint: ...

class QPaintDevice:
    def width(self) -> int: ...
    def height(self) -> int: ...

class QAction(QtCore.QObject):
    triggered: typing.ClassVar[QtCore.pyqtSignal]
    toggled: typing.ClassVar[QtCore.pyqtSignal]
    changed: typing.ClassVar[QtCore.pyqtSignal]
    @typing.overload
    def __init__(self, parent: QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, text: str | None, parent: QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, icon: QIcon, text: str | None, parent: QtCore.QObject | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setShortcut(self, shortcut: typing.Union[QKeySequence, QKeySequence.StandardKey, str, int]) -> None: ...
    def shortcut(self) -> QKeySequence: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def trigger(self) -> None: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setStatusTip(self, statusTip: str) -> None: ...
    def statusTip(self) -> str: ...

class QKeySequence:
    class StandardKey(enum.Enum):
        UnknownKey = ...
        HelpContents = ...
        WhatsThis = ...
        Open = ...
        Close = ...
        Save = ...
        New = ...
        Delete = ...
        Cut = ...
        Copy = ...
        Paste = ...
        Undo = ...
        Redo = ...
        Back = ...
        Forward = ...
        Refresh = ...
        ZoomIn = ...
        ZoomOut = ...
        Print = ...
        Find = ...
        FindNext = ...
        FindPrevious = ...
        Replace = ...
        SelectAll = ...
        Bold = ...
        Italic = ...
        Underline = ...
        Quit = ...
        FullScreen = ...

    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, key: str) -> None: ...
    @typing.overload
    def __init__(self, key: int, *args: int) -> None: ...
    @typing.overload
    def __init__(self, key: QKeySequence.StandardKey) -> None: ...
    def toString(self) -> str: ...
    @staticmethod
    def fromString(s: str) -> QKeySequence: ...

class QClipboard(QtCore.QObject):
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def clear(self) -> None: ...

class QFontMetrics:
    def __init__(self, font: QFont) -> None: ...
    def height(self) -> int: ...
    def horizontalAdvance(self, text: str) -> int: ...
    def ascent(self) -> int: ...
    def descent(self) -> int: ...
    def averageCharWidth(self) -> int: ...

class QCloseEvent(QtCore.QEvent):
    def __init__(self) -> None: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...

class QResizeEvent(QtCore.QEvent):
    def __init__(self, size: QtCore.QSize, oldSize: QtCore.QSize) -> None: ...
    def size(self) -> QtCore.QSize: ...
    def oldSize(self) -> QtCore.QSize: ...

class QShowEvent(QtCore.QEvent): ...
class QHideEvent(QtCore.QEvent): ...
class QMoveEvent(QtCore.QEvent): ...
class QEnterEvent(QtCore.QEvent): ...
class QFocusEvent(QtCore.QEvent): ...
class QKeyEvent(QtCore.QEvent): ...
class QMouseEvent(QtCore.QEvent): ...
class QWheelEvent(QtCore.QEvent): ...
class QPaintEvent(QtCore.QEvent): ...
class QContextMenuEvent(QtCore.QEvent): ...
class QActionEvent(QtCore.QEvent): ...
class QDragEnterEvent(QtCore.QEvent): ...
class QDragMoveEvent(QtCore.QEvent): ...
class QDragLeaveEvent(QtCore.QEvent): ...
class QDropEvent(QtCore.QEvent): ...

class QScreen(QtCore.QObject):
    def __init__(self, parent: QtCore.QObject | None = ...) -> None: ...
    def devicePixelRatio(self) -> float: ...
    def logicalDotsPerInch(self) -> float: ...
    def physicalDotsPerInch(self) -> float: ...
    def size(self) -> QtCore.QSize: ...
    def availableSize(self) -> QtCore.QSize: ...
    def geometry(self) -> QtCore.QRect: ...
    def availableGeometry(self) -> QtCore.QRect: ...

class QFontDatabase:
    @staticmethod
    def addApplicationFont(fileName: str) -> int: ...
    @staticmethod
    def applicationFontFamilies(id: int) -> list[str]: ...
    @staticmethod
    def families() -> list[str]: ...
    @staticmethod
    def isFixedPitch(family: str) -> bool: ...
