import enum
import typing

from PyQt6 import QtCore
from PyQt6 import QtGui

PYQT_SLOT = typing.Callable[..., object] | QtCore.pyqtBoundSignal

class QStyle(QtCore.QObject):
    def polish(self, widget: QWidget) -> None: ...
    def unpolish(self, widget: QWidget) -> None: ...

class QWidget(QtCore.QObject, QtGui.QPaintDevice):
    customContextMenuRequested: typing.ClassVar[QtCore.pyqtSignal]
    windowIconChanged: typing.ClassVar[QtCore.pyqtSignal]
    windowTitleChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    def setWindowFlags(self, type: QtCore.Qt.WindowType) -> None: ...
    def windowFlags(self) -> QtCore.Qt.WindowType: ...
    def style(self) -> QStyle | None: ...
    def setMinimumWidth(self, minw: int) -> None: ...
    def minimumWidth(self) -> int: ...
    def setMaximumWidth(self, maxw: int) -> None: ...
    def maximumWidth(self) -> int: ...
    def setMinimumHeight(self, minh: int) -> None: ...
    def minimumHeight(self) -> int: ...
    def setMaximumHeight(self, maxh: int) -> None: ...
    def maximumHeight(self) -> int: ...
    def setLayout(self, layout: QLayout) -> None: ...
    def layout(self) -> QLayout | None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def close(self) -> bool: ...
    def setWindowTitle(self, title: str) -> None: ...
    def windowTitle(self) -> str: ...
    def setWindowIcon(self, icon: QtGui.QIcon) -> None: ...
    def windowIcon(self) -> QtGui.QIcon: ...
    @typing.overload
    def resize(self, w: int, h: int) -> None: ...
    @typing.overload
    def resize(self, size: QtCore.QSize) -> None: ...
    @typing.overload
    def setMinimumSize(self, w: int, h: int) -> None: ...
    @typing.overload
    def setMinimumSize(self, size: QtCore.QSize) -> None: ...
    @typing.overload
    def setMaximumSize(self, w: int, h: int) -> None: ...
    @typing.overload
    def setMaximumSize(self, size: QtCore.QSize) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def update(self) -> None: ...
    def repaint(self) -> None: ...
    def setStyleSheet(self, styleSheet: str) -> None: ...
    def styleSheet(self) -> str: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setFocus(self) -> None: ...
    def hasFocus(self) -> bool: ...
    def parentWidget(self) -> QWidget | None: ...
    def window(self) -> QWidget: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def geometry(self) -> QtCore.QRect: ...
    @typing.overload
    def setGeometry(self, x: int, y: int, w: int, h: int) -> None: ...
    @typing.overload
    def setGeometry(self, rect: QtCore.QRect) -> None: ...
    def sizeHint(self) -> QtCore.QSize: ...
    def minimumSizeHint(self) -> QtCore.QSize: ...
    @typing.overload
    def setSizePolicy(self, horizontal: QSizePolicy.Policy, vertical: QSizePolicy.Policy) -> None: ...
    @typing.overload
    def setSizePolicy(self, policy: QSizePolicy) -> None: ...
    def sizePolicy(self) -> QSizePolicy: ...
    @typing.overload
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    @typing.overload
    def setContentsMargins(self, margins: QtCore.QMargins) -> None: ...
    def contentsMargins(self) -> QtCore.QMargins: ...
    @typing.overload
    def setFixedSize(self, w: int, h: int) -> None: ...
    @typing.overload
    def setFixedSize(self, size: QtCore.QSize) -> None: ...
    def setFixedWidth(self, w: int) -> None: ...
    def setFixedHeight(self, h: int) -> None: ...
    def setObjectName(self, name: str) -> None: ...
    def setFont(self, font: QtGui.QFont) -> None: ...
    def font(self) -> QtGui.QFont: ...
    def setCursor(self, cursor: QtGui.QCursor | QtCore.Qt.CursorShape) -> None: ...
    def setContextMenuPolicy(self, policy: QtCore.Qt.ContextMenuPolicy) -> None: ...
    def setFocusPolicy(self, policy: QtCore.Qt.FocusPolicy) -> None: ...
    def addActions(self, actions: typing.Iterable[QtGui.QAction]) -> None: ...
    @typing.overload
    def addAction(self, icon: QtGui.QIcon, text: str | None) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(
        self, icon: QtGui.QIcon, text: str | None, slot: PYQT_SLOT, type: QtCore.Qt.ConnectionType = ...
    ) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(
        self,
        icon: QtGui.QIcon,
        text: str | None,
        shortcut: typing.Union[QtGui.QKeySequence, QtGui.QKeySequence.StandardKey, str | None, int],
    ) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(
        self,
        icon: QtGui.QIcon,
        text: str | None,
        shortcut: typing.Union[QtGui.QKeySequence, QtGui.QKeySequence.StandardKey, str | None, int],
        slot: PYQT_SLOT,
        type: QtCore.Qt.ConnectionType = ...,
    ) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(self, text: str | None) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(
        self, text: str | None, shortcut: typing.Union[QtGui.QKeySequence, QtGui.QKeySequence.StandardKey, str | None, int]
    ) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(self, text: str | None, slot: PYQT_SLOT, type: QtCore.Qt.ConnectionType = ...) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(
        self,
        text: str | None,
        shortcut: typing.Union[QtGui.QKeySequence, QtGui.QKeySequence.StandardKey, str | None, int],
        slot: PYQT_SLOT,
        type: QtCore.Qt.ConnectionType = ...,
    ) -> QtGui.QAction | None: ...
    @typing.overload
    def addAction(self, action: QtGui.QAction | None) -> None: ...
    def closeEvent(self, a0: QtGui.QCloseEvent | None, /) -> None: ...
    def resizeEvent(self, a0: QtGui.QResizeEvent | None, /) -> None: ...
    def showEvent(self, a0: QtGui.QShowEvent | None, /) -> None: ...
    def hideEvent(self, a0: QtGui.QHideEvent | None, /) -> None: ...
    def moveEvent(self, a0: QtGui.QMoveEvent | None, /) -> None: ...
    def enterEvent(self, a0: QtGui.QEnterEvent | None, /) -> None: ...
    def leaveEvent(self, a0: QtCore.QEvent | None, /) -> None: ...
    def focusInEvent(self, a0: QtGui.QFocusEvent | None, /) -> None: ...
    def focusOutEvent(self, a0: QtGui.QFocusEvent | None, /) -> None: ...
    def keyPressEvent(self, a0: QtGui.QKeyEvent | None, /) -> None: ...
    def keyReleaseEvent(self, a0: QtGui.QKeyEvent | None, /) -> None: ...
    def mousePressEvent(self, a0: QtGui.QMouseEvent | None, /) -> None: ...
    def mouseReleaseEvent(self, a0: QtGui.QMouseEvent | None, /) -> None: ...
    def mouseMoveEvent(self, a0: QtGui.QMouseEvent | None, /) -> None: ...
    def mouseDoubleClickEvent(self, a0: QtGui.QMouseEvent | None, /) -> None: ...
    def wheelEvent(self, a0: QtGui.QWheelEvent | None, /) -> None: ...
    def paintEvent(self, a0: QtGui.QPaintEvent | None, /) -> None: ...
    def contextMenuEvent(self, a0: QtGui.QContextMenuEvent | None, /) -> None: ...
    def event(self, a0: QtCore.QEvent | None, /) -> bool: ...
    def actions(self) -> list[QtGui.QAction]: ...
    def winId(self) -> int: ...
    def grab(self, rectangle: QtCore.QRect = ...) -> QtGui.QPixmap: ...

class QDialog(QWidget):
    class DialogCode(enum.Enum):
        Rejected = ...
        Accepted = ...

    Accepted: typing.ClassVar[QDialog.DialogCode]
    Rejected: typing.ClassVar[QDialog.DialogCode]
    accepted: typing.ClassVar[QtCore.pyqtSignal]
    rejected: typing.ClassVar[QtCore.pyqtSignal]
    finished: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    def done(self, result: int) -> None: ...
    def result(self) -> int: ...
    def setModal(self, modal: bool) -> None: ...
    def isModal(self) -> bool: ...
    def open(self) -> None: ...

class QFrame(QWidget):
    class Shape(enum.Enum):
        NoFrame = ...
        Box = ...
        Panel = ...
        StyledPanel = ...
        HLine = ...
        VLine = ...
        WinPanel = ...

    class Shadow(enum.Enum):
        Plain = ...
        Raised = ...
        Sunken = ...

    def __init__(self, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    def setFrameStyle(self, style: int | QFrame.Shape) -> None: ...
    def setFrameShape(self, shape: QFrame.Shape) -> None: ...
    def frameShape(self) -> QFrame.Shape: ...
    def setFrameShadow(self, shadow: QFrame.Shadow) -> None: ...
    def frameShadow(self) -> QFrame.Shadow: ...
    def setLineWidth(self, width: int) -> None: ...
    def lineWidth(self) -> int: ...

class QScrollBar(QWidget):
    valueChanged: typing.ClassVar[QtCore.pyqtSignal]
    sliderPressed: typing.ClassVar[QtCore.pyqtSignal]
    sliderReleased: typing.ClassVar[QtCore.pyqtSignal]
    sliderMoved: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, orientation: QtCore.Qt.Orientation = ..., parent: QWidget | None = ...) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def setMaximum(self, max: int) -> None: ...
    def minimum(self) -> int: ...
    def maximum(self) -> int: ...
    def setRange(self, min: int, max: int) -> None: ...
    def setSingleStep(self, step: int) -> None: ...
    def singleStep(self) -> int: ...
    def setPageStep(self, step: int) -> None: ...
    def pageStep(self) -> int: ...

class QAbstractScrollArea(QFrame):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setHorizontalScrollBarPolicy(self, policy: QtCore.Qt.ScrollBarPolicy) -> None: ...
    def setVerticalScrollBarPolicy(self, policy: QtCore.Qt.ScrollBarPolicy) -> None: ...
    def horizontalScrollBar(self) -> QScrollBar: ...
    def verticalScrollBar(self) -> QScrollBar: ...
    def setHorizontalScrollBar(self, scrollBar: QScrollBar) -> None: ...
    def setVerticalScrollBar(self, scrollBar: QScrollBar) -> None: ...
    def viewport(self) -> QWidget | None: ...

class QMainWindow(QWidget):
    def __init__(self, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def menuBar(self) -> QMenuBar | None: ...
    def setStatusBar(self, statusbar: QStatusBar) -> None: ...
    @typing.overload
    def addToolBar(self, area: QtCore.Qt.ToolBarArea, toolbar: QToolBar) -> None: ...
    @typing.overload
    def addToolBar(self, toolbar: QToolBar) -> None: ...
    @typing.overload
    def addToolBar(self, title: str) -> QToolBar: ...
    def setCentralWidget(self, widget: QWidget | None) -> None: ...
    def centralWidget(self) -> QWidget | None: ...
    def setMenuBar(self, menubar: QMenuBar | None) -> None: ...
    def menuBar(self) -> QMenuBar | None: ...
    def setStatusBar(self, statusbar: QStatusBar | None) -> None: ...
    def statusBar(self) -> QStatusBar | None: ...
    @typing.overload
    def addToolBar(self, area: QtCore.Qt.ToolBarArea, toolbar: QToolBar | None) -> None: ...
    @typing.overload
    def addToolBar(self, toolbar: QToolBar | None) -> None: ...
    @typing.overload
    def addToolBar(self, title: str | None) -> QToolBar | None: ...
    def removeToolBar(self, toolbar: QToolBar | None) -> None: ...
    def addDockWidget(self, area: QtCore.Qt.DockWidgetArea, dockwidget: typing.Any, orientation: QtCore.Qt.Orientation = ...) -> None: ...
    class DockOption(enum.Flag):
        AnimatedDocks = ...
        AllowNestedDocks = ...
        AllowTabbedDocks = ...
        ForceTabbedDocks = ...
        VerticalTabs = ...
        GroupedDragging = ...

    def setDockOptions(self, options: QMainWindow.DockOption) -> None: ...
    def dockOptions(self) -> QMainWindow.DockOption: ...
    def setToolButtonStyle(self, toolButtonStyle: QtCore.Qt.ToolButtonStyle) -> None: ...
    def toolButtonStyle(self) -> QtCore.Qt.ToolButtonStyle: ...
    def setIconSize(self, iconSize: QtCore.QSize) -> None: ...
    def iconSize(self) -> QtCore.QSize: ...
    def createPopupMenu(self) -> QMenu | None: ...
    def saveState(self, version: int = ...) -> QtCore.QByteArray: ...
    def restoreState(self, state: typing.Union[QtCore.QByteArray, bytes, bytearray, memoryview], version: int = ...) -> bool: ...
    def setMenuWidget(self, menubar: QWidget | None) -> None: ...
    def menuWidget(self) -> QWidget | None: ...

class QLabel(QFrame):
    linkActivated: typing.ClassVar[QtCore.pyqtSignal]
    linkHovered: typing.ClassVar[QtCore.pyqtSignal]
    @typing.overload
    def __init__(self, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    @typing.overload
    def __init__(self, text: str, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPixmap(self, pixmap: QtGui.QPixmap) -> None: ...
    def pixmap(self) -> QtGui.QPixmap: ...
    def setAlignment(self, alignment: QtCore.Qt.AlignmentFlag) -> None: ...
    def alignment(self) -> QtCore.Qt.AlignmentFlag: ...
    def setWordWrap(self, on: bool) -> None: ...
    def wordWrap(self) -> bool: ...
    def setOpenExternalLinks(self, open: bool) -> None: ...
    def openExternalLinks(self) -> bool: ...
    def setTextInteractionFlags(self, flags: QtCore.Qt.TextInteractionFlag) -> None: ...
    def textInteractionFlags(self) -> QtCore.Qt.TextInteractionFlag: ...
    def setScaledContents(self, scaled: bool) -> None: ...
    def hasScaledContents(self) -> bool: ...
    def setTextFormat(self, format: QtCore.Qt.TextFormat) -> None: ...
    def setIndent(self, indent: int) -> None: ...
    def setMargin(self, margin: int) -> None: ...
    def setBuddy(self, buddy: QWidget | None) -> None: ...
    def buddy(self) -> QWidget | None: ...

class QAbstractButton(QWidget):
    pressed: typing.ClassVar[QtCore.pyqtSignal]
    released: typing.ClassVar[QtCore.pyqtSignal]
    clicked: typing.ClassVar[QtCore.pyqtSignal]
    toggled: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QtGui.QIcon) -> None: ...
    def icon(self) -> QtGui.QIcon: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def click(self) -> None: ...
    def setDown(self, down: bool) -> None: ...
    def isDown(self) -> bool: ...

class QPushButton(QAbstractButton):
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setDefault(self, default: bool) -> None: ...
    def isDefault(self) -> bool: ...
    def setFlat(self, flat: bool) -> None: ...
    def isFlat(self) -> bool: ...
    def setMenu(self, menu: QMenu | None) -> None: ...
    def menu(self) -> QMenu | None: ...

class QCheckBox(QAbstractButton):
    stateChanged: typing.ClassVar[QtCore.pyqtSignal]
    checkStateChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setTristate(self, tristate: bool = ...) -> None: ...
    def isTristate(self) -> bool: ...
    def checkState(self) -> QtCore.Qt.CheckState: ...
    def setCheckState(self, state: QtCore.Qt.CheckState) -> None: ...

class QRadioButton(QAbstractButton):
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...

class QLineEdit(QWidget):
    class EchoMode(enum.Enum):
        Normal = ...
        NoEcho = ...
        Password = ...
        PasswordEchoOnEdit = ...

    textChanged: typing.ClassVar[QtCore.pyqtSignal]
    textEdited: typing.ClassVar[QtCore.pyqtSignal]
    returnPressed: typing.ClassVar[QtCore.pyqtSignal]
    editingFinished: typing.ClassVar[QtCore.pyqtSignal]
    selectionChanged: typing.ClassVar[QtCore.pyqtSignal]
    cursorPositionChanged: typing.ClassVar[QtCore.pyqtSignal]
    inputRejected: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, contents: str = ..., parent: QWidget | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def placeholderText(self) -> str: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def setEchoMode(self, mode: QLineEdit.EchoMode) -> None: ...
    def echoMode(self) -> QLineEdit.EchoMode: ...
    def clear(self) -> None: ...
    def selectAll(self) -> None: ...
    def setMaxLength(self, length: int) -> None: ...
    def maxLength(self) -> int: ...
    def setCursorPosition(self, pos: int) -> None: ...
    def cursorPosition(self) -> int: ...
    def setClearButtonEnabled(self, enable: bool) -> None: ...
    def isClearButtonEnabled(self) -> bool: ...
    def setValidator(self, validator: typing.Any) -> None: ...
    @typing.overload
    def addAction(self, action: QtGui.QAction | None) -> None: ...
    @typing.overload
    def addAction(self, action: QtGui.QAction | None, position: QLineEdit.ActionPosition) -> None: ...
    @typing.overload
    def addAction(self, icon: QtGui.QIcon, position: QLineEdit.ActionPosition) -> QtGui.QAction | None: ...
    class ActionPosition(enum.Enum):
        LeadingPosition = ...
        TrailingPosition = ...

class QTextEdit(QAbstractScrollArea):
    textChanged: typing.ClassVar[QtCore.pyqtSignal]
    selectionChanged: typing.ClassVar[QtCore.pyqtSignal]
    cursorPositionChanged: typing.ClassVar[QtCore.pyqtSignal]
    copyAvailable: typing.ClassVar[QtCore.pyqtSignal]
    undoAvailable: typing.ClassVar[QtCore.pyqtSignal]
    redoAvailable: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def toHtml(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...
    def setHtml(self, html: str) -> None: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def clear(self) -> None: ...
    def append(self, text: str) -> None: ...
    def document(self) -> QtGui.QTextDocument: ...
    def setDocument(self, document: QtGui.QTextDocument | None) -> None: ...

class QPlainTextEdit(QAbstractScrollArea):
    textChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def clear(self) -> None: ...
    def appendPlainText(self, text: str) -> None: ...
    def document(self) -> QtGui.QTextDocument: ...
    def setTabStopDistance(self, distance: float) -> None: ...
    def tabStopDistance(self) -> float: ...
    def setLineWrapMode(self, mode: QPlainTextEdit.LineWrapMode) -> None: ...
    def moveCursor(self, operation: QtGui.QTextCursor.MoveOperation, mode: int = ...) -> None: ...
    def setTextCursor(self, cursor: QtGui.QTextCursor) -> None: ...
    def textCursor(self) -> QtGui.QTextCursor: ...
    def centerCursor(self) -> None: ...
    class LineWrapMode(enum.Enum):
        NoWrap = ...
        WidgetWidth = ...

class QTreeWidgetItem:
    def __init__(self, *args: typing.Any) -> None: ...
    def text(self, column: int) -> str: ...
    def setText(self, column: int, text: str) -> None: ...
    def child(self, index: int) -> QTreeWidgetItem | None: ...
    def setExpanded(self, expand: bool) -> None: ...

class QTreeWidget(QAbstractScrollArea):
    itemClicked: typing.ClassVar[QtCore.pyqtSignal]
    itemDoubleClicked: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setHeaderHidden(self, hide: bool) -> None: ...
    def clear(self) -> None: ...
    def addTopLevelItem(self, item: QTreeWidgetItem) -> None: ...
    def topLevelItem(self, index: int) -> QTreeWidgetItem | None: ...

class QComboBox(QWidget):
    currentIndexChanged: typing.ClassVar[QtCore.pyqtSignal]
    currentTextChanged: typing.ClassVar[QtCore.pyqtSignal]
    activated: typing.ClassVar[QtCore.pyqtSignal]
    highlighted: typing.ClassVar[QtCore.pyqtSignal]
    textActivated: typing.ClassVar[QtCore.pyqtSignal]
    textHighlighted: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def addItem(self, text: str, userData: typing.Any = ...) -> None: ...
    def addItems(self, texts: typing.Iterable[str]) -> None: ...
    def insertItem(self, index: int, text: str, userData: typing.Any = ...) -> None: ...
    def removeItem(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentText(self) -> str: ...
    def setCurrentText(self, text: str) -> None: ...
    def currentData(self, role: int = ...) -> typing.Any: ...
    def count(self) -> int: ...
    def itemText(self, index: int) -> str: ...
    def itemData(self, index: int, role: int = ...) -> typing.Any: ...
    def setItemText(self, index: int, text: str) -> None: ...
    def setItemData(self, index: int, data: typing.Any, role: int = ...) -> None: ...
    def findText(self, text: str, flags: QtCore.Qt.MatchFlag = ...) -> int: ...
    def findData(self, data: typing.Any, role: int = ..., flags: QtCore.Qt.MatchFlag = ...) -> int: ...
    def setEditable(self, editable: bool) -> None: ...
    def isEditable(self) -> bool: ...
    def setMinimumContentsLength(self, characters: int) -> None: ...
    def setMaxVisibleItems(self, maxItems: int) -> None: ...
    def setInsertPolicy(self, policy: QComboBox.InsertPolicy) -> None: ...
    class InsertPolicy(enum.Enum):
        NoInsert = ...
        InsertAtTop = ...
        InsertAtCurrent = ...
        InsertAtBottom = ...
        InsertAfterCurrent = ...
        InsertBeforeCurrent = ...
        InsertAlphabetically = ...

class QSpinBox(QWidget):
    valueChanged: typing.ClassVar[QtCore.pyqtSignal]
    textChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, max: int) -> None: ...
    def maximum(self) -> int: ...
    def setRange(self, min: int, max: int) -> None: ...
    def setSingleStep(self, step: int) -> None: ...
    def singleStep(self) -> int: ...
    def setPrefix(self, prefix: str) -> None: ...
    def setSuffix(self, suffix: str) -> None: ...

class QDoubleSpinBox(QWidget):
    valueChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setValue(self, value: float) -> None: ...
    def value(self) -> float: ...
    def setMinimum(self, min: float) -> None: ...
    def setMaximum(self, max: float) -> None: ...
    def setRange(self, min: float, max: float) -> None: ...
    def setDecimals(self, prec: int) -> None: ...

class QProgressBar(QWidget):
    valueChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def setMaximum(self, max: int) -> None: ...
    def setRange(self, min: int, max: int) -> None: ...
    def reset(self) -> None: ...
    def setFormat(self, format: str) -> None: ...
    def format(self) -> str: ...
    def setTextVisible(self, visible: bool) -> None: ...

class QProgressDialog(QDialog):
    canceled: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(
        self,
        labelText: str = ...,
        cancelButtonText: str = ...,
        minimum: int = ...,
        maximum: int = ...,
        parent: QWidget | None = ...,
        flags: QtCore.Qt.WindowType = ...,
    ) -> None: ...
    def setValue(self, progress: int) -> None: ...
    def value(self) -> int: ...
    def setLabelText(self, text: str) -> None: ...
    def wasCanceled(self) -> bool: ...
    def setMinimum(self, minimum: int) -> None: ...
    def setMaximum(self, maximum: int) -> None: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def cancel(self) -> None: ...
    def reset(self) -> None: ...
    def setWindowModality(self, modality: QtCore.Qt.WindowModality) -> None: ...
    def setMinimumDuration(self, ms: int) -> None: ...
    def setAutoClose(self, close: bool) -> None: ...
    def setAutoReset(self, reset: bool) -> None: ...

class QGroupBox(QWidget):
    toggled: typing.ClassVar[QtCore.pyqtSignal]
    clicked: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, title: str = ..., parent: QWidget | None = ...) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...

class QSplitter(QFrame):
    splitterMoved: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, orientation: QtCore.Qt.Orientation = ..., parent: QWidget | None = ...) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def insertWidget(self, index: int, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def count(self) -> int: ...
    def setSizes(self, list: typing.Iterable[int]) -> None: ...
    def sizes(self) -> list[int]: ...
    def setOrientation(self, orientation: QtCore.Qt.Orientation) -> None: ...
    def orientation(self) -> QtCore.Qt.Orientation: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...
    def setCollapsible(self, index: int, collapsible: bool) -> None: ...
    def isCollapsible(self, index: int) -> bool: ...
    def setHandleWidth(self, width: int) -> None: ...
    def handleWidth(self) -> int: ...

class QTabWidget(QWidget):
    currentChanged: typing.ClassVar[QtCore.pyqtSignal]
    tabCloseRequested: typing.ClassVar[QtCore.pyqtSignal]
    tabBarClicked: typing.ClassVar[QtCore.pyqtSignal]
    tabBarDoubleClicked: typing.ClassVar[QtCore.pyqtSignal]
    class TabPosition(enum.Enum):
        North = ...
        South = ...
        West = ...
        East = ...

    class TabShape(enum.Enum):
        Rounded = ...
        Triangular = ...

    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @typing.overload
    def addTab(self, widget: QWidget, label: str) -> int: ...
    @typing.overload
    def addTab(self, widget: QWidget, icon: QtGui.QIcon, label: str) -> int: ...
    def insertTab(self, index: int, widget: QWidget, label: str) -> int: ...
    def removeTab(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentWidget(self) -> QWidget | None: ...
    def setCurrentWidget(self, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def count(self) -> int: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def tabText(self, index: int) -> str: ...
    def setTabText(self, index: int, text: str) -> None: ...
    def setTabEnabled(self, index: int, enabled: bool) -> None: ...
    def isTabEnabled(self, index: int) -> bool: ...
    def setTabsClosable(self, closable: bool) -> None: ...
    def tabsClosable(self) -> bool: ...
    def setMovable(self, movable: bool) -> None: ...
    def isMovable(self) -> bool: ...

class QScrollArea(QAbstractScrollArea):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def widget(self) -> QWidget | None: ...
    def setWidgetResizable(self, resizable: bool) -> None: ...
    def widgetResizable(self) -> bool: ...

class QStackedWidget(QFrame):
    currentChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def addWidget(self, widget: QWidget) -> int: ...
    def insertWidget(self, index: int, widget: QWidget) -> int: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentWidget(self) -> QWidget | None: ...
    def setCurrentWidget(self, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def count(self) -> int: ...
    def indexOf(self, widget: QWidget) -> int: ...

class QAbstractItemView(QAbstractScrollArea):
    class SelectionBehavior(enum.Enum):
        SelectItems = ...
        SelectRows = ...
        SelectColumns = ...

    class SelectionMode(enum.Enum):
        NoSelection = ...
        SingleSelection = ...
        MultiSelection = ...
        ExtendedSelection = ...
        ContiguousSelection = ...

    class EditTrigger(enum.Flag):
        NoEditTriggers = ...
        CurrentChanged = ...
        DoubleClicked = ...
        SelectedClicked = ...
        EditKeyPressed = ...
        AnyKeyPressed = ...
        AllEditTriggers = ...

    def selectionModel(self) -> typing.Any: ...
    def setSelectionBehavior(self, behavior: QAbstractItemView.SelectionBehavior) -> None: ...
    def setSelectionMode(self, mode: QAbstractItemView.SelectionMode) -> None: ...
    def setEditTriggers(self, triggers: QAbstractItemView.EditTrigger) -> None: ...
    def setAlternatingRowColors(self, enable: bool) -> None: ...
    def alternatingRowColors(self) -> bool: ...

class QHeaderView(QAbstractItemView):
    class ResizeMode(enum.Enum):
        Interactive = ...
        Fixed = ...
        Stretch = ...
        ResizeToContents = ...

    def setSectionResizeMode(self, *args: typing.Any) -> None: ...
    def setStretchLastSection(self, stretch: bool) -> None: ...
    def hideSection(self, logicalIndex: int) -> None: ...
    def showSection(self, logicalIndex: int) -> None: ...
    def resizeSection(self, logicalIndex: int, size: int) -> None: ...

class QTableWidget(QAbstractItemView):
    cellClicked: typing.ClassVar[QtCore.pyqtSignal]
    cellDoubleClicked: typing.ClassVar[QtCore.pyqtSignal]
    itemClicked: typing.ClassVar[QtCore.pyqtSignal]
    itemDoubleClicked: typing.ClassVar[QtCore.pyqtSignal]
    itemSelectionChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, rows: int = ..., columns: int = ..., parent: QWidget | None = ...) -> None: ...
    def setRowCount(self, rows: int) -> None: ...
    def rowCount(self) -> int: ...
    def setColumnCount(self, columns: int) -> None: ...
    def columnCount(self) -> int: ...
    def setItem(self, row: int, column: int, item: QTableWidgetItem | None) -> None: ...
    def item(self, row: int, column: int) -> QTableWidgetItem | None: ...
    def setHorizontalHeaderLabels(self, labels: typing.Iterable[str]) -> None: ...
    def setVerticalHeaderLabels(self, labels: typing.Iterable[str]) -> None: ...
    def horizontalHeader(self) -> QHeaderView: ...
    def verticalHeader(self) -> QHeaderView: ...
    def clear(self) -> None: ...
    def clearContents(self) -> None: ...
    def currentRow(self) -> int: ...
    def currentColumn(self) -> int: ...
    def setCurrentCell(self, row: int, column: int) -> None: ...
    def selectRow(self, row: int) -> None: ...
    def selectedItems(self) -> list[QTableWidgetItem]: ...
    def insertRow(self, row: int) -> None: ...
    def removeRow(self, row: int) -> None: ...
    def setShowGrid(self, show: bool) -> None: ...
    def showGrid(self) -> bool: ...

class QTableWidgetItem:
    def __init__(self, text: str = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setData(self, role: int | QtCore.Qt.ItemDataRole, value: typing.Any) -> None: ...
    def data(self, role: int | QtCore.Qt.ItemDataRole) -> typing.Any: ...
    def setFlags(self, flags: QtCore.Qt.ItemFlag) -> None: ...
    def flags(self) -> QtCore.Qt.ItemFlag: ...
    def setToolTip(self, tip: str) -> None: ...
    def setTextAlignment(self, alignment: int | QtCore.Qt.AlignmentFlag) -> None: ...
    def setForeground(self, brush: typing.Union[QtGui.QColor, QtGui.QBrush]) -> None: ...
    def setBackground(self, brush: typing.Union[QtGui.QColor, QtGui.QBrush]) -> None: ...
    def font(self) -> QtGui.QFont: ...
    def setFont(self, font: QtGui.QFont) -> None: ...

class QListWidget(QAbstractItemView):
    itemClicked: typing.ClassVar[QtCore.pyqtSignal]
    itemDoubleClicked: typing.ClassVar[QtCore.pyqtSignal]
    itemSelectionChanged: typing.ClassVar[QtCore.pyqtSignal]
    currentItemChanged: typing.ClassVar[QtCore.pyqtSignal]
    currentRowChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @typing.overload
    def addItem(self, item: str) -> None: ...
    @typing.overload
    def addItem(self, item: QListWidgetItem) -> None: ...
    def addItems(self, labels: typing.Iterable[str]) -> None: ...
    def insertItem(self, row: int, item: typing.Union[str, QListWidgetItem]) -> None: ...
    def item(self, row: int) -> QListWidgetItem | None: ...
    def takeItem(self, row: int) -> QListWidgetItem | None: ...
    def count(self) -> int: ...
    def currentItem(self) -> QListWidgetItem | None: ...
    def setCurrentItem(self, item: QListWidgetItem) -> None: ...
    def currentRow(self) -> int: ...
    def setCurrentRow(self, row: int) -> None: ...
    def row(self, item: QListWidgetItem) -> int: ...
    def clear(self) -> None: ...
    def selectedItems(self) -> list[QListWidgetItem]: ...
    def findItems(self, text: str, flags: QtCore.Qt.MatchFlag) -> list[QListWidgetItem]: ...

class QListWidgetItem:
    def __init__(self, text: str = ..., listview: QListWidget | None = ..., type: int = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setData(self, role: int | QtCore.Qt.ItemDataRole, value: typing.Any) -> None: ...
    def data(self, role: int | QtCore.Qt.ItemDataRole) -> typing.Any: ...
    def setFlags(self, flags: QtCore.Qt.ItemFlag) -> None: ...
    def flags(self) -> QtCore.Qt.ItemFlag: ...
    def setIcon(self, icon: QtGui.QIcon) -> None: ...
    def icon(self) -> QtGui.QIcon: ...
    def setToolTip(self, tip: str) -> None: ...
    def setSelected(self, select: bool) -> None: ...
    def isSelected(self) -> bool: ...
    def setFont(self, font: QtGui.QFont) -> None: ...
    def font(self) -> QtGui.QFont: ...
    def setForeground(self, brush: QtGui.QColor | QtGui.QBrush) -> None: ...
    def foreground(self) -> QtGui.QBrush: ...
    def setBackground(self, brush: QtGui.QColor | QtGui.QBrush) -> None: ...
    def background(self) -> QtGui.QBrush: ...
    def setTextAlignment(self, alignment: int | QtCore.Qt.AlignmentFlag) -> None: ...
    def setSizeHint(self, size: QtCore.QSize) -> None: ...
    def sizeHint(self) -> QtCore.QSize: ...

class QSizePolicy:
    class Policy(enum.Enum):
        Fixed = ...
        Minimum = ...
        Maximum = ...
        Preferred = ...
        MinimumExpanding = ...
        Expanding = ...
        Ignored = ...

    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, horizontal: QSizePolicy.Policy, vertical: QSizePolicy.Policy, type: QSizePolicy.ControlType = ...) -> None: ...
    def horizontalPolicy(self) -> QSizePolicy.Policy: ...
    def verticalPolicy(self) -> QSizePolicy.Policy: ...
    def setHorizontalPolicy(self, policy: QSizePolicy.Policy) -> None: ...
    def setVerticalPolicy(self, policy: QSizePolicy.Policy) -> None: ...
    def horizontalStretch(self) -> int: ...
    def verticalStretch(self) -> int: ...
    def setHorizontalStretch(self, stretchFactor: int) -> None: ...
    def setVerticalStretch(self, stretchFactor: int) -> None: ...
    class ControlType(enum.Flag):
        DefaultType = ...

class QLayoutItem:
    def widget(self) -> QWidget | None: ...
    def layout(self) -> QLayout | None: ...

class QLayout(QtCore.QObject, QLayoutItem):
    def addWidget(self, widget: QWidget) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    @typing.overload
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    @typing.overload
    def setContentsMargins(self, margins: QtCore.QMargins) -> None: ...
    def contentsMargins(self) -> QtCore.QMargins: ...
    def setSpacing(self, spacing: int) -> None: ...
    def spacing(self) -> int: ...
    def count(self) -> int: ...
    def itemAt(self, index: int) -> QLayoutItem | None: ...
    def takeAt(self, index: int) -> QLayoutItem | None: ...
    def setAlignment(self, *args: typing.Any) -> bool: ...
    def addItem(self, item: QLayoutItem) -> None: ...
    def removeItem(self, item: QLayoutItem) -> None: ...

class QBoxLayout(QLayout):
    class Direction(enum.Enum):
        LeftToRight = ...
        RightToLeft = ...
        TopToBottom = ...
        BottomToTop = ...

    def __init__(self, direction: QBoxLayout.Direction, parent: QWidget | None = ...) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int = ...) -> None: ...
    def insertLayout(self, index: int, layout: QLayout, stretch: int = ...) -> None: ...
    def addStretch(self, stretch: int = ...) -> None: ...
    def insertStretch(self, index: int, stretch: int = ...) -> None: ...
    def addSpacing(self, size: int) -> None: ...
    def insertSpacing(self, index: int, size: int) -> None: ...
    def insertWidget(self, index: int, widget: QWidget, stretch: int = ..., alignment: QtCore.Qt.AlignmentFlag = ...) -> None: ...
    def addWidget(self, widget: QWidget, stretch: int = ..., alignment: QtCore.Qt.AlignmentFlag = ...) -> None: ...

class QVBoxLayout(QBoxLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QHBoxLayout(QBoxLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QFormLayout(QLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def addRow(self, *args: typing.Any) -> None: ...
    def insertRow(self, row: int, *args: typing.Any) -> None: ...
    def rowCount(self) -> int: ...
    def setLabelAlignment(self, alignment: QtCore.Qt.AlignmentFlag) -> None: ...

class QGridLayout(QLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def addWidget(
        self,
        widget: QWidget,
        row: int = ...,
        column: int = ...,
        rowSpan: int = ...,
        columnSpan: int = ...,
        alignment: QtCore.Qt.AlignmentFlag = ...,
    ) -> None: ...
    def addLayout(
        self, layout: QLayout, row: int, column: int, rowSpan: int = ..., columnSpan: int = ..., alignment: QtCore.Qt.AlignmentFlag = ...
    ) -> None: ...
    def setRowStretch(self, row: int, stretch: int) -> None: ...
    def setColumnStretch(self, column: int, stretch: int) -> None: ...
    def setRowMinimumHeight(self, row: int, minSize: int) -> None: ...
    def setColumnMinimumWidth(self, column: int, minSize: int) -> None: ...

class QDialogButtonBox(QWidget):
    class StandardButton(enum.Flag):
        NoButton = ...
        Ok = ...
        Save = ...
        SaveAll = ...
        Open = ...
        Yes = ...
        YesToAll = ...
        No = ...
        NoToAll = ...
        Abort = ...
        Retry = ...
        Ignore = ...
        Close = ...
        Cancel = ...
        Discard = ...
        Help = ...
        Apply = ...
        Reset = ...
        RestoreDefaults = ...

    accepted: typing.ClassVar[QtCore.pyqtSignal]
    rejected: typing.ClassVar[QtCore.pyqtSignal]
    clicked: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(
        self, buttons: QDialogButtonBox.StandardButton = ..., orientation: QtCore.Qt.Orientation = ..., parent: QWidget | None = ...
    ) -> None: ...
    def addButton(self, *args: typing.Any) -> QPushButton: ...
    def button(self, which: QDialogButtonBox.StandardButton) -> QPushButton | None: ...
    def buttons(self) -> list[QPushButton]: ...
    def clear(self) -> None: ...
    def setStandardButtons(self, buttons: QDialogButtonBox.StandardButton) -> None: ...
    def standardButtons(self) -> QDialogButtonBox.StandardButton: ...

class QMessageBox(QDialog):
    class StandardButton(enum.Flag):
        NoButton = ...
        Ok = ...
        Save = ...
        SaveAll = ...
        Open = ...
        Yes = ...
        YesToAll = ...
        No = ...
        NoToAll = ...
        Abort = ...
        Retry = ...
        Ignore = ...
        Close = ...
        Cancel = ...
        Discard = ...
        Help = ...
        Apply = ...
        Reset = ...
        RestoreDefaults = ...

    class Icon(enum.Enum):
        NoIcon = ...
        Information = ...
        Warning = ...
        Critical = ...
        Question = ...

    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @staticmethod
    def information(
        parent: QWidget | None,
        title: str,
        text: str,
        buttons: QMessageBox.StandardButton = ...,
        defaultButton: QMessageBox.StandardButton = ...,
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def warning(
        parent: QWidget | None,
        title: str,
        text: str,
        buttons: QMessageBox.StandardButton = ...,
        defaultButton: QMessageBox.StandardButton = ...,
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def critical(
        parent: QWidget | None,
        title: str,
        text: str,
        buttons: QMessageBox.StandardButton = ...,
        defaultButton: QMessageBox.StandardButton = ...,
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def question(
        parent: QWidget | None,
        title: str,
        text: str,
        buttons: QMessageBox.StandardButton = ...,
        defaultButton: QMessageBox.StandardButton = ...,
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def about(parent: QWidget | None, title: str, text: str) -> None: ...
    def setIcon(self, icon: QMessageBox.Icon) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def setText(self, text: str) -> None: ...
    def setInformativeText(self, text: str) -> None: ...
    def setDetailedText(self, text: str) -> None: ...
    def setStandardButtons(self, buttons: QMessageBox.StandardButton) -> None: ...
    def setDefaultButton(self, button: typing.Union[QPushButton, QMessageBox.StandardButton]) -> None: ...
    def addButton(self, *args: typing.Any) -> QPushButton | None: ...

class QFileDialog(QDialog):
    class AcceptMode(enum.Enum):
        AcceptOpen = ...
        AcceptSave = ...

    class FileMode(enum.Enum):
        AnyFile = ...
        ExistingFile = ...
        Directory = ...
        ExistingFiles = ...

    @staticmethod
    def getOpenFileName(
        parent: QWidget | None = ...,
        caption: str = ...,
        directory: str = ...,
        filter: str = ...,
        initialFilter: str = ...,
        options: QFileDialog.Option = ...,
    ) -> tuple[str, str]: ...
    @staticmethod
    def getOpenFileNames(
        parent: QWidget | None = ...,
        caption: str = ...,
        directory: str = ...,
        filter: str = ...,
        initialFilter: str = ...,
        options: QFileDialog.Option = ...,
    ) -> tuple[list[str], str]: ...
    @staticmethod
    def getSaveFileName(
        parent: QWidget | None = ...,
        caption: str = ...,
        directory: str = ...,
        filter: str = ...,
        initialFilter: str = ...,
        options: QFileDialog.Option = ...,
    ) -> tuple[str, str]: ...
    @staticmethod
    def getExistingDirectory(
        parent: QWidget | None = ..., caption: str = ..., directory: str = ..., options: QFileDialog.Option = ...
    ) -> str: ...
    class Option(enum.Flag):
        ShowDirsOnly = ...
        DontResolveSymlinks = ...
        DontConfirmOverwrite = ...
        DontUseNativeDialog = ...
        ReadOnly = ...
        HideNameFilterDetails = ...

class QInputDialog(QDialog):
    @staticmethod
    def getText(
        parent: QWidget | None, title: str, label: str, echo: QLineEdit.EchoMode = ..., text: str = ..., flags: QtCore.Qt.WindowType = ...
    ) -> tuple[str, bool]: ...
    @staticmethod
    def getInt(
        parent: QWidget | None,
        title: str,
        label: str,
        value: int = ...,
        min: int = ...,
        max: int = ...,
        step: int = ...,
        flags: QtCore.Qt.WindowType = ...,
    ) -> tuple[int, bool]: ...
    @staticmethod
    def getDouble(
        parent: QWidget | None,
        title: str,
        label: str,
        value: float = ...,
        min: float = ...,
        max: float = ...,
        decimals: int = ...,
        flags: QtCore.Qt.WindowType = ...,
    ) -> tuple[float, bool]: ...
    @staticmethod
    def getItem(
        parent: QWidget | None,
        title: str,
        label: str,
        items: typing.Sequence[str],
        current: int = ...,
        editable: bool = ...,
        flags: QtCore.Qt.WindowType = ...,
    ) -> tuple[str, bool]: ...

class QApplication(QtCore.QObject):
    def __init__(self, args: list[str] = ...) -> None: ...
    def exec(self) -> int: ...
    def setStyleSheet(self, styleSheet: str) -> None: ...
    def styleSheet(self) -> str: ...
    @staticmethod
    def instance() -> QApplication | None: ...
    @staticmethod
    def processEvents() -> None: ...
    @staticmethod
    def quit() -> None: ...
    @staticmethod
    def setStyle(style: QStyle | str) -> None: ...
    @staticmethod
    def style() -> QStyle | None: ...
    @staticmethod
    def setFont(font: QtGui.QFont) -> None: ...
    @staticmethod
    def font() -> QtGui.QFont: ...
    @staticmethod
    def setPalette(palette: QtGui.QPalette) -> None: ...
    @staticmethod
    def palette() -> QtGui.QPalette: ...
    @staticmethod
    def clipboard() -> QtGui.QClipboard: ...
    @staticmethod
    def setApplicationName(name: str) -> None: ...
    @staticmethod
    def applicationName() -> str: ...
    @staticmethod
    def setApplicationVersion(version: str) -> None: ...
    @staticmethod
    def applicationVersion() -> str: ...
    @staticmethod
    def setOrganizationName(name: str) -> None: ...
    @staticmethod
    def organizationName() -> str: ...
    @staticmethod
    def setWindowIcon(icon: QtGui.QIcon) -> None: ...
    @staticmethod
    def windowIcon() -> QtGui.QIcon: ...

class QStatusBar(QWidget):
    messageChanged: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def showMessage(self, message: str, timeout: int = ...) -> None: ...
    def currentMessage(self) -> str: ...
    def clearMessage(self) -> None: ...
    def addWidget(self, widget: QWidget, stretch: int = ...) -> None: ...
    def addPermanentWidget(self, widget: QWidget, stretch: int = ...) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...

class QToolBar(QWidget):
    actionTriggered: typing.ClassVar[QtCore.pyqtSignal]
    movableChanged: typing.ClassVar[QtCore.pyqtSignal]
    topLevelChanged: typing.ClassVar[QtCore.pyqtSignal]
    visibilityChanged: typing.ClassVar[QtCore.pyqtSignal]
    @typing.overload
    def __init__(self, title: str, parent: QWidget | None = ...) -> None: ...
    @typing.overload
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def addAction(self, action: QtGui.QAction | None) -> None: ...
    def addSeparator(self) -> QtGui.QAction | None: ...
    def addWidget(self, widget: QWidget) -> QtGui.QAction: ...
    def insertWidget(self, before: QtGui.QAction | None, widget: QWidget) -> QtGui.QAction: ...
    def clear(self) -> None: ...
    def setMovable(self, movable: bool) -> None: ...
    def isMovable(self) -> bool: ...
    def setFloatable(self, floatable: bool) -> None: ...
    def isFloatable(self) -> bool: ...
    def setFixedHeight(self, h: int) -> None: ...
    def setIconSize(self, iconSize: QtCore.QSize) -> None: ...
    def iconSize(self) -> QtCore.QSize: ...
    def setToolButtonStyle(self, toolButtonStyle: QtCore.Qt.ToolButtonStyle) -> None: ...
    def toolButtonStyle(self) -> QtCore.Qt.ToolButtonStyle: ...

class QMenu(QWidget):
    triggered: typing.ClassVar[QtCore.pyqtSignal]
    hovered: typing.ClassVar[QtCore.pyqtSignal]
    aboutToShow: typing.ClassVar[QtCore.pyqtSignal]
    aboutToHide: typing.ClassVar[QtCore.pyqtSignal]
    @typing.overload
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @typing.overload
    def __init__(self, title: str | None, parent: QWidget | None = ...) -> None: ...
    def addAction(self, action: QtGui.QAction | None) -> None: ...
    @typing.overload
    def addMenu(self, menu: QMenu | None) -> QtGui.QAction | None: ...
    @typing.overload
    def addMenu(self, title: str | None) -> QMenu | None: ...
    @typing.overload
    def addMenu(self, icon: QtGui.QIcon, title: str | None) -> QMenu | None: ...
    def addSeparator(self) -> QtGui.QAction | None: ...
    def clear(self) -> None: ...
    @typing.overload
    def exec(self) -> QtGui.QAction | None: ...
    @typing.overload
    def exec(self, p: QtCore.QPoint, action: QtGui.QAction | None = ...) -> QtGui.QAction | None: ...
    def popup(self, p: QtCore.QPoint, action: QtGui.QAction | None = ...) -> None: ...
    def activeAction(self) -> QtGui.QAction | None: ...
    def setActiveAction(self, act: QtGui.QAction | None) -> None: ...
    def defaultAction(self) -> QtGui.QAction | None: ...
    def setDefaultAction(self, a0: QtGui.QAction | None) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...
    def menuAction(self) -> QtGui.QAction | None: ...
    def insertSeparator(self, before: QtGui.QAction | None) -> QtGui.QAction | None: ...
    def insertMenu(self, before: QtGui.QAction | None, menu: QMenu | None) -> QtGui.QAction | None: ...
    def setIcon(self, icon: QtGui.QIcon) -> None: ...
    def icon(self) -> QtGui.QIcon: ...

class QMenuBar(QWidget):
    hovered: typing.ClassVar[QtCore.pyqtSignal]
    triggered: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @typing.overload
    def addMenu(self, menu: QMenu | None) -> QtGui.QAction | None: ...
    @typing.overload
    def addMenu(self, title: str | None) -> QMenu | None: ...
    @typing.overload
    def addMenu(self, icon: QtGui.QIcon, title: str | None) -> QMenu | None: ...
    def addAction(self, action: QtGui.QAction | None) -> None: ...
    def addSeparator(self) -> QtGui.QAction | None: ...
    def clear(self) -> None: ...
    def setNativeMenuBar(self, nativeMenuBar: bool) -> None: ...
    def isNativeMenuBar(self) -> bool: ...
    def activeAction(self) -> QtGui.QAction | None: ...
    def setActiveAction(self, action: QtGui.QAction | None) -> None: ...
    def insertSeparator(self, before: QtGui.QAction | None) -> QtGui.QAction | None: ...
    def insertMenu(self, before: QtGui.QAction | None, menu: QMenu | None) -> QtGui.QAction | None: ...

class QDockWidget(QWidget):
    dockLocationChanged: typing.ClassVar[QtCore.pyqtSignal]
    topLevelChanged: typing.ClassVar[QtCore.pyqtSignal]
    visibilityChanged: typing.ClassVar[QtCore.pyqtSignal]
    featuresChanged: typing.ClassVar[QtCore.pyqtSignal]
    class DockWidgetFeature(enum.Flag):
        DockWidgetClosable = ...
        DockWidgetMovable = ...
        DockWidgetFloatable = ...
        DockWidgetVerticalTitleBar = ...
        AllDockWidgetFeatures = ...
        NoDockWidgetFeatures = ...

    def __init__(self, title: str = ..., parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def widget(self) -> QWidget | None: ...
    def setFeatures(self, features: QDockWidget.DockWidgetFeature) -> None: ...
    def features(self) -> QDockWidget.DockWidgetFeature: ...
    def toggleViewAction(self) -> QtGui.QAction: ...

class QSlider(QWidget):
    valueChanged: typing.ClassVar[QtCore.pyqtSignal]
    sliderPressed: typing.ClassVar[QtCore.pyqtSignal]
    sliderReleased: typing.ClassVar[QtCore.pyqtSignal]
    sliderMoved: typing.ClassVar[QtCore.pyqtSignal]
    def __init__(self, orientation: QtCore.Qt.Orientation = ..., parent: QWidget | None = ...) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def setMaximum(self, max: int) -> None: ...
    def setRange(self, min: int, max: int) -> None: ...

class QToolButton(QAbstractButton):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setMenu(self, menu: QMenu | None) -> None: ...
    def menu(self) -> QMenu | None: ...
    def setDefaultAction(self, action: QtGui.QAction | None) -> None: ...
    def defaultAction(self) -> QtGui.QAction | None: ...
    def setPopupMode(self, mode: QToolButton.ToolButtonPopupMode) -> None: ...
    class ToolButtonPopupMode(enum.Enum):
        DelayedPopup = ...
        MenuButtonPopup = ...
        InstantPopup = ...

class QStyleOptionMenuItem:
    pass

class QSplashScreen(QWidget):
    messageChanged: typing.ClassVar[QtCore.pyqtSignal]
    @typing.overload
    def __init__(self, pixmap: QtGui.QPixmap = ..., f: QtCore.Qt.WindowType = ...) -> None: ...
    @typing.overload
    def __init__(self, screen: typing.Any, pixmap: QtGui.QPixmap = ..., f: QtCore.Qt.WindowType = ...) -> None: ...
    def clearMessage(self) -> None: ...
    def drawContents(self, painter: QtGui.QPainter) -> None: ...
    def finish(self, w: QWidget) -> None: ...
    def message(self) -> str: ...
    def pixmap(self) -> QtGui.QPixmap: ...
    def setPixmap(self, pixmap: QtGui.QPixmap) -> None: ...
    def showMessage(self, message: str, alignment: QtCore.Qt.AlignmentFlag = ..., color: QtGui.QColor = ...) -> None: ...
