"""
This type stub file was generated by pyright.
"""

def is_available() -> bool:
    ...

def device_count() -> int:
    ...

def set_device(device: int) -> None:
    ...

def synchronize() -> None:
    ...

def empty_cache() -> None:
    ...

def get_device_name(device: int) -> str:
    ...

def memory_allocated(device: int = ...) -> int:
    ...

class _DeviceProperties:
    name: str
    total_memory: int
    driver_version: str
    ...


def get_device_properties(device: int) -> _DeviceProperties:
    ...
