# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Zachary Flint
#
# This file is part of Intellicrack. See LICENSE for details.

from typing import Any

class Bookmark:
    offset: int
    length: int
    label: str
    color: str

    def __init__(self, offset: int, length: int, label: str, color: str) -> None: ...

class HexDocument:
    def __init__(self) -> None: ...
    @staticmethod
    def open(path: str) -> HexDocument: ...
    @staticmethod
    def open_bytes(data: bytes) -> HexDocument: ...
    def save(self, path: str) -> None: ...
    def save_as(self, path: str) -> None: ...
    def length(self) -> int: ...
    def read(self, offset: int, length: int) -> bytes: ...
    def read_byte(self, offset: int) -> int: ...
    def write_bytes(self, offset: int, data: bytes) -> None: ...
    def insert_bytes(self, offset: int, data: bytes) -> None: ...
    def delete_bytes(self, offset: int, length: int) -> None: ...
    def undo(self) -> bool: ...
    def redo(self) -> bool: ...
    def can_undo(self) -> bool: ...
    def can_redo(self) -> bool: ...
    def is_modified(self) -> bool: ...
    def search_bytes(self, pattern: bytes, max_results: int) -> list[tuple[int, int]]: ...
    def search_hex(self, pattern: str, max_results: int) -> list[tuple[int, int]]: ...
    def search_text(self, text: str, encoding: str, case_sensitive: bool, max_results: int) -> list[tuple[int, int]]: ...
    def search_regex(self, pattern: str, max_results: int) -> list[tuple[int, int]]: ...
    def replace_bytes(self, pattern: bytes, replacement: bytes) -> int: ...
    def inspect_at(self, offset: int) -> dict[str, str]: ...
    def compute_hash(self, algorithm: str) -> str: ...
    def compute_hash_range(self, start: int, end: int, algorithm: str) -> str: ...
    def byte_statistics(self) -> list[tuple[int, int]]: ...
    def add_bookmark(self, offset: int, length: int, label: str, color: str) -> int: ...
    def remove_bookmark(self, index: int) -> bool: ...
    def list_bookmarks(self) -> list[tuple[int, int, str, str]]: ...
    def apply_template(self, name: str, offset: int) -> list[dict[str, Any]]: ...
    def list_templates(self) -> list[tuple[str, str]]: ...
    def register_json_template(self, json_str: str) -> str: ...
    def remove_template(self, name: str) -> bool: ...
    def export_template_json(self, name: str) -> str: ...
    def list_templates_detailed(self) -> list[tuple[str, str, str, int]]: ...
    def file_path(self) -> str | None: ...
    def entropy(self) -> float: ...
    def entropy_map(self, block_size: int) -> list[float]: ...
    def byte_distribution_full(self) -> list[int]: ...
    def byte_type_distribution(self) -> tuple[int, int, int, int]: ...
    def digram_matrix(self) -> list[int]: ...
    def content_classification(self, block_size: int) -> list[int]: ...
    def transform_data(self, name: str, offset: int, length: int, params: dict[str, bytes]) -> bytes: ...
    def list_transforms(self) -> list[tuple[str, str, str]]: ...
    def get_patches(self) -> list[tuple[int, bytes]]: ...
    def export_patches_ips(self) -> bytes: ...
    def export_patches_ips32(self) -> bytes: ...
    def export_patches_cod(self) -> bytes: ...
    def export_patches_json(self) -> str: ...
    def import_patches_ips(self, data: bytes) -> int: ...
    def decode_text(self, offset: int, length: int, encoding: str) -> str: ...
    def encode_text_to_bytes(self, text: str, encoding: str) -> bytes: ...
    def list_encodings(self) -> list[tuple[str, str]]: ...
    def search_text_encoded(self, text: str, encoding: str, case_sensitive: bool, max_results: int) -> list[tuple[int, int]]: ...
    def search_numeric(
        self,
        value: int,
        size: int,
        signed: bool,
        big_endian: bool,
        alignment: int,
        max_results: int,
    ) -> list[tuple[int, int]]: ...
    def search_numeric_float(
        self,
        value: float,
        size: int,
        big_endian: bool,
        tolerance: float,
        alignment: int,
        max_results: int,
    ) -> list[tuple[int, int]]: ...
    def search_numeric_range(
        self,
        value_range: tuple[int, int],
        size: int,
        signed: bool,
        big_endian: bool,
        alignment: int,
        max_results: int,
    ) -> list[tuple[int, int]]: ...
    def compute_hash_custom_crc(
        self,
        byte_range: tuple[int, int],
        poly: int,
        init: int,
        width: int,
        reflect: tuple[bool, bool],
        xorout: int,
    ) -> str: ...
    @staticmethod
    def from_process_memory(pid: int, address: int, size: int) -> HexDocument: ...
    @staticmethod
    def list_process_memory_regions(pid: int) -> list[tuple[int, int, int, int]]: ...
    def export_patches_bps(self, source_data: bytes) -> bytes: ...
    def import_patches_bps(self, patch_data: bytes, source_data: bytes) -> int: ...
    def export_patches_ups(self, source_data: bytes) -> bytes: ...
    def import_patches_ups(self, patch_data: bytes, source_data: bytes) -> int: ...
    def fill_block(self, offset: int, length: int, pattern: bytes) -> None: ...
    def copy_block(self, src_offset: int, length: int, dst_offset: int) -> None: ...
    def move_block(self, src_offset: int, length: int, dst_offset: int) -> None: ...
    def swap_blocks(self, offset_a: int, len_a: int, offset_b: int, len_b: int) -> None: ...
    def get_bit(self, offset: int, bit_index: int) -> bool: ...
    def set_bit(self, offset: int, bit_index: int, value: bool) -> None: ...
    def toggle_bit(self, offset: int, bit_index: int) -> bool: ...
    def add_va_mapping(self, file_offset: int, virtual_address: int, length: int) -> None: ...
    def remove_va_mapping(self, index: int) -> bool: ...
    def list_va_mappings(self) -> list[tuple[int, int, int]]: ...
    def file_offset_to_va(self, offset: int) -> int | None: ...
    def va_to_file_offset(self, va: int) -> int | None: ...
    def extract_strings(
        self,
        min_length: int,
        include_ascii: bool,
        include_utf16: bool,
        max_results: int,
    ) -> list[dict[str, Any]]: ...
    def verify_pe_checksum(self) -> dict[str, Any]: ...
    def repair_pe_checksum(self) -> None: ...
    def get_document_memory_usage(self) -> int: ...
    def set_chunk_size_hint(self, size: int) -> None: ...
    def get_chunk_size_hint(self) -> int: ...
    def set_memory_budget_hint(self, budget: int) -> None: ...
    def get_memory_budget_hint(self) -> int: ...

def diff_files(path_a: str, path_b: str) -> dict[str, Any]: ...
def diff_bytes(data_a: bytes, data_b: bytes) -> dict[str, Any]: ...
