"""Type stubs for the intellicrack_hexcore Rust extension module."""

from typing import Any

class Bookmark:
    offset: int
    length: int
    label: str
    color: str

    def __init__(self, offset: int, length: int, label: str, color: str) -> None: ...
    def __repr__(self) -> str: ...

class HexDocument:
    def __init__(self) -> None: ...
    @staticmethod
    def open(path: str) -> HexDocument: ...
    @staticmethod
    def open_bytes(data: bytes) -> HexDocument: ...
    def save(self, path: str) -> None: ...
    def save_as(self, path: str) -> None: ...
    def length(self) -> int: ...
    def read(self, offset: int, length: int) -> bytes: ...
    def read_byte(self, offset: int) -> int: ...
    def write_bytes(self, offset: int, data: bytes) -> None: ...
    def insert_bytes(self, offset: int, data: bytes) -> None: ...
    def delete_bytes(self, offset: int, length: int) -> None: ...
    def undo(self) -> bool: ...
    def redo(self) -> bool: ...
    def can_undo(self) -> bool: ...
    def can_redo(self) -> bool: ...
    def is_modified(self) -> bool: ...
    def search_bytes(self, pattern: bytes, max_results: int) -> list[tuple[int, int]]: ...
    def search_hex(self, pattern: str, max_results: int) -> list[tuple[int, int]]: ...
    def search_text(self, text: str, encoding: str, case_sensitive: bool, max_results: int) -> list[tuple[int, int]]: ...
    def search_regex(self, pattern: str, max_results: int) -> list[tuple[int, int]]: ...
    def replace_bytes(self, pattern: list[int], replacement: list[int]) -> int: ...
    def inspect_at(self, offset: int) -> dict[str, str]: ...
    def compute_hash(self, algorithm: str) -> str: ...
    def compute_hash_range(self, start: int, end: int, algorithm: str) -> str: ...
    def byte_statistics(self) -> list[tuple[int, int]]: ...
    def add_bookmark(self, offset: int, length: int, label: str, color: str) -> int: ...
    def remove_bookmark(self, index: int) -> bool: ...
    def list_bookmarks(self) -> list[tuple[int, int, str, str]]: ...
    def apply_template(self, name: str, offset: int) -> list[dict[str, Any]]: ...
    def list_templates(self) -> list[tuple[str, str]]: ...
    def file_path(self) -> str | None: ...

def diff_files(path_a: str, path_b: str) -> dict[str, Any]: ...
def diff_bytes(data_a: bytes, data_b: bytes) -> dict[str, Any]: ...
