from collections.abc import Callable, Mapping, Sequence
from typing import Any, Literal, NotRequired, Self, TypedDict, overload

from . import _frida as _frida

__version__: str

ServerNotRunningError = _frida.ServerNotRunningError
ExecutableNotFoundError = _frida.ExecutableNotFoundError
ExecutableNotSupportedError = _frida.ExecutableNotSupportedError
ProcessNotFoundError = _frida.ProcessNotFoundError
ProcessNotRespondingError = _frida.ProcessNotRespondingError
InvalidArgumentError = _frida.InvalidArgumentError
InvalidOperationError = _frida.InvalidOperationError
PermissionDeniedError = _frida.PermissionDeniedError
AddressInUseError = _frida.AddressInUseError
TimedOutError = _frida.TimedOutError
NotSupportedError = _frida.NotSupportedError
ProtocolError = _frida.ProtocolError
TransportError = _frida.TransportError
OperationCancelledError = _frida.OperationCancelledError

ProcessTarget = int | str

class ScriptErrorMessage(TypedDict):
    type: Literal["error"]
    description: str
    stack: NotRequired[str]
    fileName: NotRequired[str]
    lineNumber: NotRequired[int]
    columnNumber: NotRequired[int]

class ScriptPayloadMessage(TypedDict):
    type: Literal["send"]
    payload: NotRequired[Any]

ScriptMessage = ScriptPayloadMessage | ScriptErrorMessage
ScriptMessageCallback = Callable[[ScriptMessage, bytes | None], None]
ScriptDestroyedCallback = Callable[[], None]

SessionDetachedCallback = Callable[
    [
        Literal[
            "application-requested",
            "process-replaced",
            "process-terminated",
            "connection-terminated",
            "device-lost",
        ],
        "Crash | None",
    ],
    None,
]

BusDetachedCallback = Callable[[], None]
BusMessageCallback = Callable[[Mapping[Any, Any], bytes | None], None]

ServiceCloseCallback = Callable[[], None]
ServiceMessageCallback = Callable[[Any], None]

DeviceSpawnAddedCallback = Callable[["Spawn"], None]
DeviceSpawnRemovedCallback = Callable[["Spawn"], None]
DeviceChildAddedCallback = Callable[["Child"], None]
DeviceChildRemovedCallback = Callable[["Child"], None]
DeviceProcessCrashedCallback = Callable[["Crash"], None]
DeviceOutputCallback = Callable[[int, int, bytes], None]
DeviceUninjectedCallback = Callable[[int], None]
DeviceLostCallback = Callable[[], None]

DeviceManagerAddedCallback = Callable[["Device"], None]
DeviceManagerRemovedCallback = Callable[["Device"], None]
DeviceManagerChangedCallback = Callable[[], None]

PortalServiceNodeJoinedCallback = Callable[[int, "Application"], None]
PortalServiceNodeLeftCallback = Callable[[int, "Application"], None]
PortalServiceNodeConnectedCallback = Callable[[int, tuple[str, int]], None]
PortalServiceNodeDisconnectedCallback = Callable[[int, tuple[str, int]], None]
PortalServiceControllerConnectedCallback = Callable[[int, tuple[str, int]], None]
PortalServiceControllerDisconnectedCallback = Callable[[int, tuple[str, int]], None]
PortalServiceAuthenticatedCallback = Callable[[int, Mapping[Any, Any]], None]
PortalServiceSubscribeCallback = Callable[[int], None]
PortalServiceMessageCallback = Callable[[int, Mapping[Any, Any], bytes | None], None]

class CompilerDiagnosticFile(TypedDict):
    path: str
    line: int
    character: int

class CompilerDiagnostic(TypedDict):
    category: str
    code: int
    file: NotRequired[CompilerDiagnosticFile]
    text: str

CompilerStartingCallback = Callable[[], None]
CompilerFinishedCallback = Callable[[], None]
CompilerOutputCallback = Callable[[str], None]
CompilerDiagnosticsCallback = Callable[[list[CompilerDiagnostic]], None]

CompilerOutputFormat = Literal["unescaped", "hex-bytes", "c-string"]
CompilerBundleFormat = Literal["esm", "iife"]
CompilerTypeCheck = Literal["full", "none"]
CompilerSourceMaps = Literal["included", "omitted"]
CompilerCompression = Literal["none", "terser"]
CompilerPlatform = Literal["neutral", "gum", "browser"]

class RPCException(Exception): ...

class _ScriptExports:
    def __init__(self, script: Script) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Any]: ...
    def __dir__(self) -> list[str]: ...

class CancellablePollFD:
    handle: int
    def __init__(self, cancellable: _frida.Cancellable) -> None: ...
    def release(self) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> int: ...
    def __exit__(self, *exc: object) -> None: ...

class Cancellable:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def on(self, signal: Literal["cancelled"], callback: Callable[[], None]) -> None: ...
    def off(self, signal: Literal["cancelled"], callback: Callable[[], None]) -> None: ...
    def cancel(self) -> None: ...
    def get_fd(self) -> int: ...
    @property
    def is_cancelled(self) -> bool: ...
    def pop_current(self) -> None: ...
    def push_current(self) -> None: ...
    def release_fd(self) -> None: ...
    def reset(self) -> None: ...
    def set_error_if_cancelled(self) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *exc: object) -> Literal[False]: ...
    @classmethod
    def get_current(cls) -> Cancellable | None: ...
    def raise_if_cancelled(self) -> None: ...
    def get_pollfd(self) -> CancellablePollFD: ...
    def connect(self, callback: Callable[[], None]) -> int: ...
    def disconnect(self, handler_id: int) -> None: ...

class Application:
    def __repr__(self) -> str: ...
    @property
    def identifier(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def parameters(self) -> dict[str, Any]: ...

class Process:
    def __repr__(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def parameters(self) -> dict[str, Any]: ...

class Spawn:
    def __repr__(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def identifier(self) -> str: ...

class Child:
    def __repr__(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def parent_pid(self) -> int: ...
    @property
    def origin(self) -> str: ...
    @property
    def identifier(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def argv(self) -> list[str]: ...
    @property
    def envp(self) -> list[str]: ...

class Crash:
    def __repr__(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def process_name(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def report(self) -> str: ...
    @property
    def parameters(self) -> dict[str, Any]: ...

class Relay:
    def __init__(self, address: str, username: str, password: str, kind: str) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def address(self) -> str: ...
    @property
    def username(self) -> str: ...
    @property
    def password(self) -> str: ...
    @property
    def kind(self) -> str: ...

class IOStream:
    def __repr__(self) -> str: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def read(self, count: int) -> bytes: ...
    def read_all(self, count: int) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def write_all(self, data: bytes) -> None: ...

class Bus:
    def is_detached(self) -> bool: ...
    def attach(self) -> None: ...
    def post(self, message: Any, data: bytes | None = ...) -> None: ...
    @overload
    def on(self, signal: Literal["detached"], callback: BusDetachedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["message"], callback: BusMessageCallback) -> None: ...
    @overload
    def off(self, signal: Literal["detached"], callback: BusDetachedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["message"], callback: BusMessageCallback) -> None: ...

class Service:
    @overload
    def on(self, signal: Literal["close"], callback: ServiceCloseCallback) -> None: ...
    @overload
    def on(self, signal: Literal["message"], callback: ServiceMessageCallback) -> None: ...
    @overload
    def off(self, signal: Literal["close"], callback: ServiceCloseCallback) -> None: ...
    @overload
    def off(self, signal: Literal["message"], callback: ServiceMessageCallback) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def activate(self) -> None: ...
    def cancel(self) -> None: ...
    def request(self, parameters: Any) -> Any: ...

class Script:
    exports_sync: _ScriptExports

    def __repr__(self) -> str: ...
    @property
    def is_destroyed(self) -> bool: ...
    def load(self) -> None: ...
    def interrupt(self) -> None: ...
    def unload(self) -> None: ...
    def terminate(self) -> None: ...
    def eternalize(self) -> None: ...
    def post(self, message: Any, data: bytes | None = ...) -> None: ...
    def enable_debugger(self, port: int = ...) -> None: ...
    def disable_debugger(self) -> None: ...
    @property
    def exports(self) -> _ScriptExports: ...
    @overload
    def on(self, signal: Literal["destroyed"], callback: ScriptDestroyedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["message"], callback: ScriptMessageCallback) -> None: ...
    @overload
    def off(self, signal: Literal["destroyed"], callback: ScriptDestroyedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["message"], callback: ScriptMessageCallback) -> None: ...
    def get_log_handler(self) -> Callable[[str, str], None]: ...
    def set_log_handler(self, handler: Callable[[str, str], None]) -> None: ...
    def default_log_handler(self, level: str, text: str) -> None: ...
    def list_exports_sync(self) -> list[str]: ...
    def list_exports(self) -> list[str]: ...

class PortalMembership:
    def terminate(self) -> None: ...

class Session:
    def __repr__(self) -> str: ...
    def on(self, signal: Literal["detached"], callback: SessionDetachedCallback) -> None: ...
    def off(self, signal: Literal["detached"], callback: SessionDetachedCallback) -> None: ...
    @property
    def is_detached(self) -> bool: ...
    @property
    def pid(self) -> int: ...
    @property
    def persist_timeout(self) -> int: ...
    def detach(self) -> None: ...
    def resume(self) -> None: ...
    def enable_child_gating(self) -> None: ...
    def disable_child_gating(self) -> None: ...
    def create_script(
        self,
        source: str,
        name: str | None = ...,
        snapshot: bytes | None = ...,
        runtime: str | None = ...,
    ) -> Script: ...
    def create_script_from_bytes(
        self,
        data: bytes,
        name: str | None = ...,
        snapshot: bytes | None = ...,
        runtime: str | None = ...,
    ) -> Script: ...
    def compile_script(
        self,
        source: str,
        name: str | None = ...,
        runtime: str | None = ...,
    ) -> bytes: ...
    def snapshot_script(
        self,
        embed_script: str,
        warmup_script: str | None = ...,
        runtime: str | None = ...,
    ) -> bytes: ...
    def setup_peer_connection(
        self,
        *,
        stun_server: str | None = ...,
        relays: Sequence[Relay] | None = ...,
    ) -> None: ...
    def join_portal(
        self,
        address: str,
        *,
        certificate: str | None = ...,
        token: str | None = ...,
        acl: Sequence[str] | None = ...,
    ) -> PortalMembership: ...

class Device:
    def __repr__(self) -> str: ...
    @overload
    def on(self, signal: Literal["spawn-added"], callback: DeviceSpawnAddedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["spawn-removed"], callback: DeviceSpawnRemovedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["child-added"], callback: DeviceChildAddedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["child-removed"], callback: DeviceChildRemovedCallback) -> None: ...
    @overload
    def on(
        self, signal: Literal["process-crashed"], callback: DeviceProcessCrashedCallback,
    ) -> None: ...
    @overload
    def on(self, signal: Literal["output"], callback: DeviceOutputCallback) -> None: ...
    @overload
    def on(self, signal: Literal["uninjected"], callback: DeviceUninjectedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["lost"], callback: DeviceLostCallback) -> None: ...
    @overload
    def off(self, signal: Literal["spawn-added"], callback: DeviceSpawnAddedCallback) -> None: ...
    @overload
    def off(
        self, signal: Literal["spawn-removed"], callback: DeviceSpawnRemovedCallback,
    ) -> None: ...
    @overload
    def off(self, signal: Literal["child-added"], callback: DeviceChildAddedCallback) -> None: ...
    @overload
    def off(
        self, signal: Literal["child-removed"], callback: DeviceChildRemovedCallback,
    ) -> None: ...
    @overload
    def off(
        self, signal: Literal["process-crashed"], callback: DeviceProcessCrashedCallback,
    ) -> None: ...
    @overload
    def off(self, signal: Literal["output"], callback: DeviceOutputCallback) -> None: ...
    @overload
    def off(self, signal: Literal["uninjected"], callback: DeviceUninjectedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["lost"], callback: DeviceLostCallback) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def icon(self) -> Any: ...
    @property
    def dtype(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def bus(self) -> Bus: ...
    @property
    def is_lost(self) -> bool: ...
    def get_bus(self) -> Bus: ...
    def override_option(self, name: str, val: Any) -> None: ...
    def query_system_parameters(self) -> dict[str, Any]: ...
    def get_frontmost_application(self, *, scope: str | None = ...) -> Application | None: ...
    def enumerate_applications(
        self,
        *,
        identifiers: Sequence[str] | None = ...,
        scope: str | None = ...,
    ) -> list[Application]: ...
    def get_process_by_pid(
        self,
        pid: int,
        *,
        timeout: int | None = ...,
        scope: str | None = ...,
    ) -> Process: ...
    def get_process_by_name(
        self,
        name: str,
        *,
        timeout: int | None = ...,
        scope: str | None = ...,
    ) -> Process: ...
    def find_process_by_pid(
        self,
        pid: int,
        *,
        timeout: int | None = ...,
        scope: str | None = ...,
    ) -> Process | None: ...
    def find_process_by_name(
        self,
        name: str,
        *,
        timeout: int | None = ...,
        scope: str | None = ...,
    ) -> Process | None: ...
    def enumerate_processes(
        self,
        *,
        pids: Sequence[int] | None = ...,
        scope: str | None = ...,
    ) -> list[Process]: ...
    def get_process(self, process_name: str) -> Process: ...
    def enable_spawn_gating(self, *, scope: str | None = ...) -> None: ...
    def disable_spawn_gating(self) -> None: ...
    def enumerate_pending_spawn(self) -> list[Spawn]: ...
    def enumerate_pending_children(self) -> list[Child]: ...
    def spawn(
        self,
        program: str | Sequence[str | bytes],
        argv: Sequence[str | bytes] | None = ...,
        envp: Mapping[str, str] | None = ...,
        env: Mapping[str, str] | None = ...,
        cwd: str | None = ...,
        stdio: str | None = ...,
        **aux: Any,
    ) -> int: ...
    def input(self, target: ProcessTarget, data: bytes) -> None: ...
    def resume(self, target: ProcessTarget) -> None: ...
    def kill(self, target: ProcessTarget) -> None: ...
    def attach(
        self,
        target: ProcessTarget,
        *,
        realm: str | None = ...,
        persist_timeout: int | None = ...,
        emulated_agent_path: str | None = ...,
        exceptor: str | None = ...,
        unwind_broker: bool | None = ...,
        exit_monitor: bool | None = ...,
        thread_suspend_monitor: bool | None = ...,
        linker_notifier_offsets: Sequence[int] | None = ...,
    ) -> Session: ...
    def inject_library_file(
        self,
        target: ProcessTarget,
        path: str,
        entrypoint: str,
        data: str,
    ) -> int: ...
    def inject_library_blob(
        self,
        target: ProcessTarget,
        blob: bytes,
        entrypoint: str,
        data: str,
    ) -> int: ...
    def open_channel(self, address: str) -> IOStream: ...
    def open_service(self, address: str) -> Service: ...
    def unpair(self) -> None: ...

class DeviceManager:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @overload
    def on(self, signal: Literal["added"], callback: DeviceManagerAddedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["removed"], callback: DeviceManagerRemovedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["changed"], callback: DeviceManagerChangedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["added"], callback: DeviceManagerAddedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["removed"], callback: DeviceManagerRemovedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["changed"], callback: DeviceManagerChangedCallback) -> None: ...
    def close(self) -> None: ...
    def get_device_by_id(self, id: str, timeout: int) -> Device: ...
    def get_device_by_type(self, type: str, timeout: int) -> Device: ...
    def find_device_by_id(self, id: str, timeout: int) -> Device | None: ...
    def find_device_by_type(self, type: str, timeout: int) -> Device | None: ...
    def enumerate_devices(self) -> list[Device]: ...
    def add_remote_device(
        self,
        address: str,
        *,
        certificate: str | None = ...,
        origin: str | None = ...,
        token: str | None = ...,
        keepalive_interval: int | None = ...,
    ) -> Device: ...
    def remove_remote_device(self, address: str) -> None: ...
    def get_device_matching(
        self,
        predicate: Callable[[Device], bool],
        timeout: int | float = ...,
    ) -> Device: ...
    def get_device(self, id: str | None, timeout: int | float = ...) -> Device: ...
    def get_local_device(self) -> Device: ...
    def get_remote_device(self) -> Device: ...
    def get_usb_device(self, timeout: int | float = ...) -> Device: ...

class Package:
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def url(self) -> str: ...

class PackageSearchResult:
    def __repr__(self) -> str: ...
    @property
    def packages(self) -> list[Package]: ...
    @property
    def total(self) -> int: ...

class PackageInstallResult:
    @property
    def packages(self) -> list[Package]: ...

class PackageManager:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def search(
        self,
        query: str,
        *,
        offset: int | None = ...,
        limit: int | None = ...,
    ) -> PackageSearchResult: ...
    def install(
        self,
        *,
        project_root: str | None = ...,
        role: str | None = ...,
        specs: Sequence[str] | None = ...,
        omits: Sequence[str] | None = ...,
    ) -> PackageInstallResult: ...
    @property
    def registry(self) -> str: ...
    @registry.setter
    def registry(self, value: str) -> None: ...

class Compiler:
    def __init__(self) -> None: ...
    @overload
    def on(self, signal: Literal["starting"], callback: CompilerStartingCallback) -> None: ...
    @overload
    def on(self, signal: Literal["finished"], callback: CompilerFinishedCallback) -> None: ...
    @overload
    def on(self, signal: Literal["output"], callback: CompilerOutputCallback) -> None: ...
    @overload
    def on(
        self, signal: Literal["diagnostics"], callback: CompilerDiagnosticsCallback,
    ) -> None: ...
    @overload
    def off(self, signal: Literal["starting"], callback: CompilerStartingCallback) -> None: ...
    @overload
    def off(self, signal: Literal["finished"], callback: CompilerFinishedCallback) -> None: ...
    @overload
    def off(self, signal: Literal["output"], callback: CompilerOutputCallback) -> None: ...
    @overload
    def off(
        self, signal: Literal["diagnostics"], callback: CompilerDiagnosticsCallback,
    ) -> None: ...
    def build(
        self,
        entrypoint: str,
        *,
        project_root: str | None = ...,
        output_format: CompilerOutputFormat | None = ...,
        bundle_format: CompilerBundleFormat | None = ...,
        type_check: CompilerTypeCheck | None = ...,
        source_maps: CompilerSourceMaps | None = ...,
        compression: CompilerCompression | None = ...,
        platform: CompilerPlatform | None = ...,
        externals: Sequence[str] | None = ...,
    ) -> str: ...
    def watch(
        self,
        entrypoint: str,
        *,
        project_root: str | None = ...,
        output_format: CompilerOutputFormat | None = ...,
        bundle_format: CompilerBundleFormat | None = ...,
        type_check: CompilerTypeCheck | None = ...,
        source_maps: CompilerSourceMaps | None = ...,
        compression: CompilerCompression | None = ...,
        platform: CompilerPlatform | None = ...,
        externals: Sequence[str] | None = ...,
    ) -> None: ...

class FileMonitor:
    def __init__(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def on(self, signal: Literal["change"], callback: Callable[..., None]) -> None: ...
    def off(self, signal: Literal["change"], callback: Callable[..., None]) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    @property
    def path(self) -> str: ...

class StaticAuthenticationService:
    def __init__(self, token: str) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def token_hash(self) -> str: ...

class AuthenticationService:
    def __init__(self) -> None: ...

class WebRequestHandler:
    def __init__(self) -> None: ...

class WebRequest:
    def __repr__(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query_string(self) -> str: ...
    @property
    def body(self) -> bytes: ...

class WebResponse:
    def __repr__(self) -> str: ...
    def add_header(self, name: str, val: str) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def body(self) -> bytes: ...

class EndpointParameters:
    def __init__(
        self,
        address: str | None = ...,
        port: int | None = ...,
        certificate: str | None = ...,
        origin: str | None = ...,
        authentication: tuple[str, Any] | None = ...,
        asset_root: str | None = ...,
        request_handler: Callable[..., Any] | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def certificate(self) -> str: ...
    @property
    def origin(self) -> str: ...
    @property
    def auth_service(self) -> AuthenticationService: ...
    @property
    def request_handler(self) -> WebRequestHandler: ...
    @request_handler.setter
    def request_handler(self, value: WebRequestHandler) -> None: ...

class ControlService:
    def start(self) -> None: ...
    def stop(self) -> None: ...

class PortalService:
    def __init__(
        self,
        cluster_params: EndpointParameters = ...,
        control_params: EndpointParameters | None = ...,
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def kick(self, connection_id: int) -> None: ...
    def post(self, connection_id: int, message: Any, data: bytes | None = ...) -> None: ...
    def narrowcast(self, tag: str, message: Any, data: bytes | None = ...) -> None: ...
    def broadcast(self, message: Any, data: bytes | None = ...) -> None: ...
    def enumerate_tags(self, connection_id: int) -> list[str]: ...
    def tag(self, connection_id: int, tag: str) -> None: ...
    def untag(self, connection_id: int, tag: str) -> None: ...
    @property
    def device(self) -> Device: ...
    @property
    def cluster_params(self) -> EndpointParameters: ...
    @property
    def control_params(self) -> EndpointParameters: ...
    @overload
    def on(
        self, signal: Literal["node-connected"], callback: PortalServiceNodeConnectedCallback,
    ) -> None: ...
    @overload
    def on(
        self, signal: Literal["node-joined"], callback: PortalServiceNodeJoinedCallback,
    ) -> None: ...
    @overload
    def on(self, signal: Literal["node-left"], callback: PortalServiceNodeLeftCallback) -> None: ...
    @overload
    def on(
        self, signal: Literal["node-disconnected"], callback: PortalServiceNodeDisconnectedCallback,
    ) -> None: ...
    @overload
    def on(
        self,
        signal: Literal["controller-connected"],
        callback: PortalServiceControllerConnectedCallback,
    ) -> None: ...
    @overload
    def on(
        self,
        signal: Literal["controller-disconnected"],
        callback: PortalServiceControllerDisconnectedCallback,
    ) -> None: ...
    @overload
    def on(
        self, signal: Literal["authenticated"], callback: PortalServiceAuthenticatedCallback,
    ) -> None: ...
    @overload
    def on(
        self, signal: Literal["subscribe"], callback: PortalServiceSubscribeCallback,
    ) -> None: ...
    @overload
    def on(self, signal: Literal["message"], callback: PortalServiceMessageCallback) -> None: ...
    @overload
    def off(
        self, signal: Literal["node-connected"], callback: PortalServiceNodeConnectedCallback,
    ) -> None: ...
    @overload
    def off(
        self, signal: Literal["node-joined"], callback: PortalServiceNodeJoinedCallback,
    ) -> None: ...
    @overload
    def off(
        self, signal: Literal["node-left"], callback: PortalServiceNodeLeftCallback,
    ) -> None: ...
    @overload
    def off(
        self, signal: Literal["node-disconnected"], callback: PortalServiceNodeDisconnectedCallback,
    ) -> None: ...
    @overload
    def off(
        self,
        signal: Literal["controller-connected"],
        callback: PortalServiceControllerConnectedCallback,
    ) -> None: ...
    @overload
    def off(
        self,
        signal: Literal["controller-disconnected"],
        callback: PortalServiceControllerDisconnectedCallback,
    ) -> None: ...
    @overload
    def off(
        self, signal: Literal["authenticated"], callback: PortalServiceAuthenticatedCallback,
    ) -> None: ...
    @overload
    def off(
        self, signal: Literal["subscribe"], callback: PortalServiceSubscribeCallback,
    ) -> None: ...
    @overload
    def off(self, signal: Literal["message"], callback: PortalServiceMessageCallback) -> None: ...

def get_device_manager() -> DeviceManager: ...
def get_device(id: str, timeout: int | float = ...) -> Device: ...
def get_device_matching(
    predicate: Callable[[Device], bool],
    timeout: int | float = ...,
) -> Device: ...
def get_local_device() -> Device: ...
def get_remote_device() -> Device: ...
def get_usb_device(timeout: int | float = ...) -> Device: ...
def enumerate_devices() -> list[Device]: ...
def query_system_parameters() -> dict[str, Any]: ...
def spawn(
    program: str | Sequence[str | bytes],
    argv: Sequence[str | bytes] | None = ...,
    envp: Mapping[str, str] | None = ...,
    env: Mapping[str, str] | None = ...,
    cwd: str | None = ...,
    stdio: str | None = ...,
    **aux: Any,
) -> int: ...
def resume(target: ProcessTarget) -> None: ...
def kill(target: ProcessTarget) -> None: ...
def attach(
    target: ProcessTarget,
    *,
    realm: str | None = ...,
    persist_timeout: int | None = ...,
    emulated_agent_path: str | None = ...,
    exceptor: str | None = ...,
    unwind_broker: bool | None = ...,
    exit_monitor: bool | None = ...,
    thread_suspend_monitor: bool | None = ...,
    linker_notifier_offsets: Sequence[int] | None = ...,
) -> Session: ...
def inject_library_file(target: ProcessTarget, path: str, entrypoint: str, data: str) -> int: ...
def inject_library_blob(target: ProcessTarget, blob: bytes, entrypoint: str, data: str) -> int: ...
def shutdown() -> None: ...
def make_auth_callback(callback: Callable[[str], Any]) -> Callable[[Any], str]: ...
