from typing import Any

__version__: str

class Process:
    pid: int
    name: str
    parameters: dict[str, Any]

class Application:
    identifier: str
    name: str
    pid: int
    parameters: dict[str, Any]

class Spawn:
    pid: int
    identifier: str

class Child:
    pid: int
    parent_pid: int
    origin: str
    identifier: str | None
    path: str | None
    envp: dict[str, str]
    argv: list[str]

class Crash:
    pid: int
    process_name: str
    summary: str
    report: str
    parameters: dict[str, Any]

class Relay:
    address: str
    username: str
    password: str
    kind: str
    def __init__(
        self,
        address: str,
        username: str,
        password: str,
        kind: str,
    ) -> None: ...

class IOStream:
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def read(self, count: int) -> bytes: ...
    def read_all(self, count: int) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def write_all(self, data: bytes) -> None: ...

class Script:
    def is_destroyed(self) -> bool: ...
    def load(self) -> None: ...
    def unload(self) -> None: ...
    def eternalize(self) -> None: ...
    def post(self, message: str, **kwargs: Any) -> None: ...
    def enable_debugger(self, **kwargs: Any) -> None: ...
    def disable_debugger(self) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...
    def create_script(self, source: str, **kwargs: Any) -> Script: ...
    def create_script_from_bytes(self, data: bytes, **kwargs: Any) -> Script: ...
    def compile_script(self, source: str, **kwargs: Any) -> bytes: ...
    def snapshot_script(self, embed_script: str, **kwargs: Any) -> bytes: ...

class Session:
    def is_detached(self) -> bool: ...
    def detach(self) -> None: ...
    def resume(self) -> None: ...
    def enable_child_gating(self) -> None: ...
    def disable_child_gating(self) -> None: ...
    def create_script(self, source: str, **kwargs: Any) -> Script: ...
    def create_script_from_bytes(self, data: bytes, **kwargs: Any) -> Script: ...
    def compile_script(self, source: str, **kwargs: Any) -> bytes: ...
    def snapshot_script(self, embed_script: str, **kwargs: Any) -> bytes: ...
    def setup_peer_connection(self, **kwargs: Any) -> None: ...
    def join_portal(self, address: str, **kwargs: Any) -> Any: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class Bus:
    def attach(self) -> None: ...
    def post(self, message: str, **kwargs: Any) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class Device:
    id: str
    name: str
    icon: Any
    type: str
    bus: Bus | None
    def is_lost(self) -> bool: ...
    def query_system_parameters(self) -> dict[str, Any]: ...
    def get_frontmost_application(self, **kwargs: Any) -> Application | None: ...
    def enumerate_applications(self, **kwargs: Any) -> list[Application]: ...
    def enumerate_processes(self, **kwargs: Any) -> list[Process]: ...
    def get_process(self, process_name: str) -> Process: ...
    def enable_spawn_gating(self) -> None: ...
    def disable_spawn_gating(self) -> None: ...
    def enumerate_pending_spawn(self) -> list[Spawn]: ...
    def enumerate_pending_children(self) -> list[Child]: ...
    def spawn(self, program: str, **kwargs: Any) -> int: ...
    def input(self, pid: int, data: bytes) -> None: ...
    def resume(self, pid: int) -> None: ...
    def kill(self, pid: int) -> None: ...
    def attach(self, pid: int, **kwargs: Any) -> Session: ...
    def inject_library_file(self, pid: int, path: str, entrypoint: str, data: str) -> int: ...
    def inject_library_blob(self, pid: int, blob: bytes, entrypoint: str, data: str) -> int: ...
    def open_channel(self, address: str) -> IOStream: ...
    def open_service(self, address: str) -> Any: ...
    def unpair(self) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class DeviceManager:
    def close(self) -> None: ...
    def get_device_matching(self, predicate: Any, timeout: int = ...) -> Device: ...
    def enumerate_devices(self) -> list[Device]: ...
    def add_remote_device(self, address: str, **kwargs: Any) -> Device: ...
    def remove_remote_device(self, address: str) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class Cancellable:
    def is_cancelled(self) -> bool: ...
    def raise_if_cancelled(self) -> None: ...
    def get_fd(self) -> int: ...
    def release_fd(self) -> None: ...
    def push_current(self) -> None: ...
    def pop_current(self) -> None: ...
    @staticmethod
    def get_current() -> Cancellable: ...
    def connect(self, callback: Any) -> int: ...
    def disconnect(self, handler_id: int) -> None: ...
    def cancel(self) -> None: ...

class FileMonitor:
    def __init__(self, path: str) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class EndpointParameters:
    def __init__(self, **kwargs: Any) -> None: ...

class PortalMembership:
    def terminate(self) -> None: ...

class PortalService:
    device: Device
    def __init__(self, *args: Any) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def post(self, connection_id: int, message: str, **kwargs: Any) -> None: ...
    def narrowcast(self, tag: str, message: str, **kwargs: Any) -> None: ...
    def broadcast(self, message: str, **kwargs: Any) -> None: ...
    def enumerate_tags(self, connection_id: int) -> list[str]: ...
    def tag(self, connection_id: int, tag: str) -> None: ...
    def untag(self, connection_id: int, tag: str) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class Compiler:
    def __init__(self) -> None: ...
    def build(self, entrypoint: str, **kwargs: Any) -> str: ...
    def watch(self, entrypoint: str, **kwargs: Any) -> None: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class PackageManager:
    registry: str | None
    def __init__(self) -> None: ...
    def search(self, query: str, **kwargs: Any) -> PackageSearchResult: ...
    def install(self, **kwargs: Any) -> PackageInstallResult: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class PackageSearchResult: ...
class PackageInstallResult: ...

class Service:
    def __init__(self, impl: Any) -> None: ...
    def activate(self) -> None: ...
    def cancel(self) -> None: ...
    def request(self, parameters: Any) -> Any: ...
    def on(self, signal: str, callback: Any) -> None: ...
    def off(self, signal: str, callback: Any) -> None: ...

class ServerNotRunningError(Exception): ...
class ExecutableNotFoundError(Exception): ...
class ExecutableNotSupportedError(Exception): ...
class ProcessNotFoundError(Exception): ...
class ProcessNotRespondingError(Exception): ...
class InvalidArgumentError(Exception): ...
class InvalidOperationError(Exception): ...
class PermissionDeniedError(Exception): ...
class AddressInUseError(Exception): ...
class TimedOutError(Exception): ...
class NotSupportedError(Exception): ...
class ProtocolError(Exception): ...
class TransportError(Exception): ...
class OperationCancelledError(Exception): ...
