from collections.abc import Callable, Sequence
from typing import Any, Literal, NotRequired, TypedDict, overload

from . import _frida

ProcessTarget = int | str

class ScriptErrorMessage(TypedDict):
    type: Literal["error"]
    description: str
    stack: NotRequired[str]
    fileName: NotRequired[str]
    lineNumber: NotRequired[int]
    columnNumber: NotRequired[int]

class ScriptPayloadMessage(TypedDict):
    type: Literal["send"]
    payload: NotRequired[Any]

ScriptMessage = ScriptPayloadMessage | ScriptErrorMessage
ScriptMessageCallback = Callable[[ScriptMessage, bytes | None], None]
ScriptDestroyedCallback = Callable[[], None]

class Script:
    exports_sync: ScriptExportsSync
    exports_async: ScriptExportsAsync

    def __init__(self, impl: _frida.Script) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def is_destroyed(self) -> bool: ...
    def load(self) -> None: ...
    def unload(self) -> None: ...
    def eternalize(self) -> None: ...
    def post(self, message: Any, data: str | bytes | None = ...) -> None: ...
    def enable_debugger(self, port: int | None = ...) -> None: ...
    def disable_debugger(self) -> None: ...
    @overload
    def on(self, signal: Literal["message"], callback: ScriptMessageCallback) -> None: ...
    @overload
    def on(self, signal: Literal["destroyed"], callback: ScriptDestroyedCallback) -> None: ...
    @overload
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    @overload
    def off(self, signal: Literal["message"], callback: ScriptMessageCallback) -> None: ...
    @overload
    def off(self, signal: Literal["destroyed"], callback: ScriptDestroyedCallback) -> None: ...
    @overload
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def get_log_handler(self) -> Callable[[str, str], None]: ...
    def set_log_handler(self, handler: Callable[[str, str], None]) -> None: ...
    def default_log_handler(self, level: str, text: str) -> None: ...
    def list_exports_sync(self) -> list[str]: ...
    def list_exports(self) -> list[str]: ...

class Session:
    def __init__(self, impl: _frida.Session) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def is_detached(self) -> bool: ...
    def detach(self) -> None: ...
    def resume(self) -> None: ...
    def enable_child_gating(self) -> None: ...
    def disable_child_gating(self) -> None: ...
    def create_script(
        self,
        source: str,
        name: str | None = ...,
        snapshot: bytes | None = ...,
        runtime: str | None = ...,
    ) -> Script: ...
    def create_script_from_bytes(
        self,
        data: bytes,
        name: str | None = ...,
        snapshot: bytes | None = ...,
        runtime: str | None = ...,
    ) -> Script: ...
    def compile_script(
        self,
        source: str,
        name: str | None = ...,
        runtime: str | None = ...,
    ) -> bytes: ...
    def snapshot_script(
        self,
        embed_script: str,
        warmup_script: str | None = ...,
        runtime: str | None = ...,
    ) -> bytes: ...
    def setup_peer_connection(
        self,
        stun_server: str | None = ...,
        relays: Sequence[_frida.Relay] | None = ...,
    ) -> None: ...
    def join_portal(
        self,
        address: str,
        certificate: str | None = ...,
        token: str | None = ...,
        acl: list[str] | tuple[str] | None = ...,
    ) -> PortalMembership: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class Device:
    id: str
    name: str
    icon: Any
    type: str
    bus: Bus

    def __init__(self, device: _frida.Device) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def is_lost(self) -> bool: ...
    def query_system_parameters(self) -> dict[str, Any]: ...
    def get_frontmost_application(
        self, scope: str | None = ...,
    ) -> _frida.Application | None: ...
    def enumerate_applications(
        self,
        identifiers: Sequence[str] | None = ...,
        scope: str | None = ...,
    ) -> list[_frida.Application]: ...
    def enumerate_processes(
        self,
        pids: Sequence[int] | None = ...,
        scope: str | None = ...,
    ) -> list[_frida.Process]: ...
    def get_process(self, process_name: str) -> _frida.Process: ...
    def enable_spawn_gating(self) -> None: ...
    def disable_spawn_gating(self) -> None: ...
    def enumerate_pending_spawn(self) -> list[_frida.Spawn]: ...
    def enumerate_pending_children(self) -> list[_frida.Child]: ...
    def spawn(
        self,
        program: str | Sequence[str | bytes],
        argv: Sequence[str | bytes] | None = ...,
        envp: dict[str, str] | None = ...,
        env: dict[str, str] | None = ...,
        cwd: str | None = ...,
        stdio: str | None = ...,
        **kwargs: Any,
    ) -> int: ...
    def input(self, target: ProcessTarget, data: bytes) -> None: ...
    def resume(self, target: ProcessTarget) -> None: ...
    def kill(self, target: ProcessTarget) -> None: ...
    def attach(
        self,
        target: ProcessTarget,
        realm: str | None = ...,
        persist_timeout: int | None = ...,
    ) -> Session: ...
    def inject_library_file(
        self, target: ProcessTarget, path: str, entrypoint: str, data: str,
    ) -> int: ...
    def inject_library_blob(
        self, target: ProcessTarget, blob: bytes, entrypoint: str, data: str,
    ) -> int: ...
    def open_channel(self, address: str) -> IOStream: ...
    def open_service(self, address: str) -> Service: ...
    def unpair(self) -> None: ...
    def get_bus(self) -> Bus: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class DeviceManager:
    def __init__(self, impl: _frida.DeviceManager) -> None: ...
    def __repr__(self) -> str: ...
    def get_local_device(self) -> Device: ...
    def get_remote_device(self) -> Device: ...
    def get_usb_device(self, timeout: int = ...) -> Device: ...
    def get_device(self, id: str | None, timeout: int = ...) -> Device: ...
    def get_device_matching(
        self, predicate: Callable[[Device], bool], timeout: int = ...,
    ) -> Device: ...
    def enumerate_devices(self) -> list[Device]: ...
    def add_remote_device(
        self,
        address: str,
        certificate: str | None = ...,
        origin: str | None = ...,
        token: str | None = ...,
        keepalive_interval: int | None = ...,
    ) -> Device: ...
    def remove_remote_device(self, address: str) -> None: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class IOStream:
    def __init__(self, impl: _frida.IOStream) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def read(self, count: int) -> bytes: ...
    def read_all(self, count: int) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def write_all(self, data: bytes) -> None: ...

class PortalMembership:
    def __init__(self, impl: _frida.PortalMembership) -> None: ...
    def terminate(self) -> None: ...

class ScriptExportsSync:
    def __init__(self, script: Script) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Any]: ...
    def __dir__(self) -> list[str]: ...

class ScriptExportsAsync:
    def __init__(self, script: Script) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Any]: ...
    def __dir__(self) -> list[str]: ...

class Bus:
    def __init__(self, impl: _frida.Bus) -> None: ...
    def attach(self) -> None: ...
    def post(self, message: Any, data: str | bytes | None = ...) -> None: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class Service:
    def __init__(self, impl: _frida.Service) -> None: ...
    def activate(self) -> None: ...
    def cancel(self) -> None: ...
    def request(self, parameters: Any) -> Any: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class EndpointParameters:
    _impl: _frida.EndpointParameters
    def __init__(
        self,
        address: str | None = ...,
        port: int | None = ...,
        certificate: str | None = ...,
        origin: str | None = ...,
        authentication: tuple[str, str | Callable[[str], Any]] | None = ...,
        asset_root: str | None = ...,
    ) -> None: ...

class PortalService:
    device: Any
    def __init__(
        self,
        cluster_params: EndpointParameters = ...,
        control_params: EndpointParameters | None = ...,
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def post(self, connection_id: int, message: Any, data: str | bytes | None = ...) -> None: ...
    def narrowcast(self, tag: str, message: Any, data: str | bytes | None = ...) -> None: ...
    def broadcast(self, message: Any, data: str | bytes | None = ...) -> None: ...
    def enumerate_tags(self, connection_id: int) -> list[str]: ...
    def tag(self, connection_id: int, tag: str) -> None: ...
    def untag(self, connection_id: int, tag: str) -> None: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class Compiler:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def build(self, entrypoint: str, **kwargs: Any) -> str: ...
    def watch(self, entrypoint: str, **kwargs: Any) -> None: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class PackageManager:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def registry(self) -> str | None: ...
    @registry.setter
    def registry(self, value: str | None) -> None: ...
    def search(self, query: str, **kwargs: Any) -> Any: ...
    def install(self, **kwargs: Any) -> Any: ...
    def on(self, signal: str, callback: Callable[..., Any]) -> None: ...
    def off(self, signal: str, callback: Callable[..., Any]) -> None: ...

class Cancellable:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def is_cancelled(self) -> bool: ...
    def raise_if_cancelled(self) -> None: ...
    def get_pollfd(self) -> Any: ...
    @classmethod
    def get_current(cls) -> _frida.Cancellable: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...
    def connect(self, callback: Callable[..., Any]) -> int: ...
    def disconnect(self, handler_id: int) -> None: ...
    def cancel(self) -> None: ...

class RPCException(Exception): ...

def get_device_manager() -> DeviceManager: ...
def cancellable(f: Callable[..., Any]) -> Callable[..., Any]: ...
