# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Zachary Flint
#
# This file is part of Intellicrack. See LICENSE for details.
"""Coverage for the Windows Sandbox backend paths that need no running sandbox.

Windows Sandbox cannot start in the test container, so nothing here launches
one. The guards that refuse work without a running sandbox or a shared folder
are driven directly. The host-side YARA scan reads real files in a temporary
shared folder. The host-side minidump helpers dump a real child process the
test spawns. The guest command channel is exercised with the production
dispatcher script, generated by the sandbox with its shared path pointed at a
temporary directory and run under the real ``powershell.exe``; one guest has
only a copy of ``cmd.exe`` on its ``PATH`` so the guest tools a real sandbox
provides (``powershell``, ``xcopy``, ``mofcomp``) are absent, and the other
keeps the host ``PATH``.
"""

from __future__ import annotations

import asyncio
import contextlib
import msvcrt
import os
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path
from typing import IO, TYPE_CHECKING, Final, cast

import pytest

import intellicrack.sandbox.windows as windows_module
from intellicrack.sandbox.base import SandboxConfig, SandboxError
from intellicrack.sandbox.windows import WindowsSandbox, resolve_anti_evasion_profile


if TYPE_CHECKING:
    from collections.abc import Callable, Coroutine, Generator, Iterator


_POWERSHELL: Final[str] = "powershell.exe"
_DISPATCHER_READY_TIMEOUT: Final[float] = 90.0
_DISPATCHER_POLL_SECONDS: Final[float] = 0.25
_COMMAND_BUDGET_SECONDS: Final[int] = 90
_STAGING_WAIT_SECONDS: Final[float] = 60.0
_STAGING_POLL_SECONDS: Final[float] = 0.02
_CHILD_READY_MARKER: Final[str] = "ready"
_CHILD_SCRIPT: Final[str] = "import sys\nprint('ready', flush=True)\nsys.stdin.read()\n"
_CHILD_STOP_TIMEOUT: Final[float] = 30.0
_NONEXISTENT_PID: Final[int] = 0xFFFFFFFC
_MINIDUMP_SIGNATURE: Final[bytes] = b"MDMP"
_INJECTOR_STRINGS: Final[bytes] = b"MZ\x90\x00" + b"\x00" * 16 + b"CreateRemoteThread\x00VirtualAllocEx\x00"
_CUSTOM_RULE_MARKER: Final[bytes] = b"critcov-marker-7f3a"
_CUSTOM_RULES: Final[str] = 'rule CustomMarker {\n    strings:\n        $m = "critcov-marker-7f3a"\n    condition:\n        $m\n}\n'

_read_dispatcher_result = cast(
    "Callable[[object], Coroutine[object, object, tuple[int, str, str] | None]]",
    getattr(windows_module, "_read_dispatcher_result"),
)
_make_dispatcher_paths = cast(
    "Callable[[Path, Path, Path, Path], object]",
    getattr(windows_module, "_DispatcherPaths"),
)
_minidump_via_dbghelp = cast(
    "Callable[[int, Path], tuple[bool, str]]",
    getattr(windows_module, "_minidump_via_dbghelp"),
)
_win_handle_from_file = cast(
    "Callable[[IO[bytes]], int | None]",
    getattr(windows_module, "_win_handle_from_file"),
)


class _HostBoundSandbox(WindowsSandbox):
    """A ``WindowsSandbox`` bound to directories on this host, with no guest launched.

    Only what a live sandbox would supply is arranged: where the shared folder
    is, and whether the sandbox counts as running. Every method under test is
    the production one; the wrappers exist so tests can reach protected
    members without touching them from outside the class.
    """

    def __init__(self, config: SandboxConfig | None = None) -> None:
        """Create the sandbox with a bounded command budget.

        Args:
            config: Optional sandbox configuration; a short command timeout is
                used when omitted so a broken guest cannot stall a test.
        """
        super().__init__(config or SandboxConfig(timeout_seconds=_COMMAND_BUDGET_SECONDS))

    def bind(self, shared: Path, *, running: bool) -> None:
        """Point the sandbox at a host directory and set its running state.

        Args:
            shared: Directory standing in for the guest's shared folder.
            running: Whether the sandbox should report ``running``.
        """
        self.SANDBOX_SHARED_PATH = str(shared)
        self._shared_folder = shared
        self.state.status = "running" if running else "stopped"

    def mark_running(self) -> None:
        """Set the sandbox status to ``running`` without a shared folder."""
        self.state.status = "running"

    def dispatcher_source(self) -> str:
        """Return the in-guest dispatcher PowerShell the sandbox would stage.

        Returns:
            str: The generated dispatcher script source.
        """
        return self._dispatcher_ps1_source()

    def shared_folder(self) -> Path:
        """Return the host directory bound as the shared folder.

        Returns:
            Path: The bound shared folder.
        """
        assert self._shared_folder is not None
        return self._shared_folder

    def ready_flag_path(self) -> Path:
        """Return the flag file the dispatcher writes when it comes up.

        Returns:
            Path: Host path of the readiness flag.
        """
        return self.shared_folder() / "flags" / self.DISPATCHER_READY_MARKER

    async def query_wmi_identity(self) -> dict[str, str]:
        """Run the production WMI identity query through the guest channel.

        Returns:
            dict[str, str]: The identity values the guest reported.
        """
        return await self._query_wmi_identity()

    async def apply_wmi_hijack(self, machine_name: str) -> dict[str, object]:
        """Run the production WMI hijack step for the default profile.

        Args:
            machine_name: Computer name to inject.

        Returns:
            dict[str, object]: Result mapping from the hijack step.
        """
        return await self._apply_wmi_hijack(resolve_anti_evasion_profile("default"), machine_name)

    async def minidump(self, pid: int, dump_path: Path) -> bool:
        """Run the production host-side minidump with its procdump fallback.

        Args:
            pid: Process to dump.
            dump_path: Destination dump path.

        Returns:
            bool: Whether a dump file was produced.
        """
        return await self._minidump_via_procdump(pid, dump_path)


def _copy_cmd_into(directory: Path) -> None:
    """Place a copy of the host ``cmd.exe`` in ``directory``.

    Args:
        directory: Directory that will be the only entry on a guest ``PATH``.

    Raises:
        AssertionError: If ``cmd.exe`` cannot be found on the host.
    """
    cmd = shutil.which("cmd.exe")
    if cmd is None:
        message = "cmd.exe is required to run the guest dispatcher"
        raise AssertionError(message)
    shutil.copy2(cmd, directory / "cmd.exe")


@contextlib.contextmanager
def _dispatcher_running(root: Path, *, tools_on_path: bool) -> Generator[_HostBoundSandbox]:
    """Run the real dispatcher script against a temporary shared folder.

    Args:
        root: Scratch directory for the share and the dispatcher script.
        tools_on_path: When true the dispatcher keeps the host ``PATH``; when
            false its ``PATH`` holds only a copy of ``cmd.exe``, so commands
            that need ``powershell``, ``xcopy`` or ``mofcomp`` are not found.

    Yields:
        _HostBoundSandbox: A running sandbox whose dispatcher is polling.
    """
    powershell = shutil.which(_POWERSHELL)
    assert powershell is not None, "this test needs the real powershell.exe to run the dispatcher"

    share = root / "IntellicrackShared"
    share.mkdir()
    sandbox = _HostBoundSandbox()
    sandbox.bind(share, running=True)

    environment = dict(os.environ)
    if not tools_on_path:
        guest_bin = root / "guest_bin"
        guest_bin.mkdir()
        _copy_cmd_into(guest_bin)
        environment["PATH"] = str(guest_bin)

    script = root / "dispatcher.ps1"
    script.write_text(sandbox.dispatcher_source(), encoding="utf-8")
    process = subprocess.Popen(
        [powershell, "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", str(script)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        env=environment,
    )
    try:
        deadline = time.monotonic() + _DISPATCHER_READY_TIMEOUT
        while time.monotonic() < deadline and not sandbox.ready_flag_path().is_file():
            if process.poll() is not None:
                pytest.fail("the dispatcher exited before signalling ready")
            time.sleep(_DISPATCHER_POLL_SECONDS)
        assert sandbox.ready_flag_path().is_file(), "the real dispatcher never signalled ready"
        yield sandbox
    finally:
        process.terminate()
        try:
            process.wait(timeout=_DISPATCHER_READY_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=_DISPATCHER_READY_TIMEOUT)


@pytest.fixture
def guest_without_tools(tmp_path: Path) -> Iterator[_HostBoundSandbox]:
    """Provide a dispatcher whose guest has no ``powershell``, ``xcopy`` or ``mofcomp``.

    Args:
        tmp_path: Directory for the shared folder and dispatcher script.

    Yields:
        _HostBoundSandbox: A running sandbox bound to the dispatcher.
    """
    with _dispatcher_running(tmp_path, tools_on_path=False) as sandbox:
        yield sandbox


@pytest.fixture
def guest_with_host_tools(tmp_path: Path) -> Iterator[_HostBoundSandbox]:
    """Provide a dispatcher whose guest sees the host ``PATH``.

    Args:
        tmp_path: Directory for the shared folder and dispatcher script.

    Yields:
        _HostBoundSandbox: A running sandbox bound to the dispatcher.
    """
    with _dispatcher_running(tmp_path, tools_on_path=True) as sandbox:
        yield sandbox


@pytest.fixture
def idle_child() -> Iterator[subprocess.Popen[str]]:
    """Spawn a Python child that prints a ready marker and then blocks on stdin.

    Yields:
        subprocess.Popen[str]: The running child process.
    """
    child = subprocess.Popen(
        [sys.executable, "-c", _CHILD_SCRIPT],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    try:
        assert child.stdout is not None
        assert child.stdout.readline().strip() == _CHILD_READY_MARKER
        yield child
    finally:
        child.kill()
        child.communicate(timeout=_CHILD_STOP_TIMEOUT)


def _running_sandbox_without_share() -> _HostBoundSandbox:
    """Build a sandbox that is running but has no shared folder.

    Returns:
        _HostBoundSandbox: A sandbox in the running state with no share.
    """
    sandbox = _HostBoundSandbox()
    sandbox.mark_running()
    return sandbox


def _share_with_output(root: Path) -> Path:
    """Create a shared folder holding an ``output`` directory.

    Args:
        root: Parent directory.

    Returns:
        Path: The shared folder.
    """
    share = root / "share"
    (share / "output").mkdir(parents=True)
    return share


class TestScreenshotGuards:
    """``capture_screenshot`` refuses to run without a running sandbox and a share."""

    def test_a_stopped_sandbox_is_refused(self) -> None:
        """A sandbox that is not running cannot take a screenshot."""
        with pytest.raises(SandboxError, match="Sandbox is not running"):
            asyncio.run(_HostBoundSandbox().capture_screenshot())

    def test_a_running_sandbox_without_a_share_is_refused(self) -> None:
        """A running sandbox with no shared folder has nowhere to read the image from."""
        with pytest.raises(SandboxError, match="Shared folder not initialized"):
            asyncio.run(_running_sandbox_without_share().capture_screenshot())


class TestAntiEvasionGuards:
    """The anti-evasion entry points refuse to stage a MOF without a share."""

    def test_apply_anti_evasion_without_a_share_is_refused(self) -> None:
        """A running sandbox with no shared folder cannot stage the MOF file."""
        with pytest.raises(SandboxError, match="shared folder not initialized"):
            asyncio.run(_running_sandbox_without_share().apply_anti_evasion("default"))

    def test_the_wmi_hijack_step_without_a_share_is_refused(self) -> None:
        """The hijack step itself rejects a missing share before writing anything."""
        with pytest.raises(SandboxError, match="shared folder not initialized"):
            asyncio.run(_running_sandbox_without_share().apply_wmi_hijack("DESKTOP-ABC123"))


class TestMemoryDumpGuards:
    """``dump_memory`` checks its preconditions before it validates the target."""

    def test_a_stopped_sandbox_is_refused(self) -> None:
        """A sandbox that is not running cannot dump a guest process."""
        with pytest.raises(SandboxError, match="Sandbox is not running"):
            asyncio.run(_HostBoundSandbox().dump_memory(target_pid=1234))

    def test_a_running_sandbox_without_a_share_is_refused(self) -> None:
        """A running sandbox with no shared folder has nowhere to receive the dump."""
        with pytest.raises(SandboxError, match="Shared folder not initialized"):
            asyncio.run(_running_sandbox_without_share().dump_memory(target_pid=1234))


class TestExtractDroppedFilesGuards:
    """``extract_dropped_files`` refuses to run without a running sandbox and a share."""

    def test_a_stopped_sandbox_is_refused(self) -> None:
        """A sandbox that is not running has no dropped files to collect."""
        with pytest.raises(SandboxError, match="Sandbox is not running"):
            asyncio.run(_HostBoundSandbox().extract_dropped_files())

    def test_a_running_sandbox_without_a_share_is_refused(self) -> None:
        """A running sandbox with no shared folder cannot stage the extraction."""
        with pytest.raises(SandboxError, match="Shared folder not initialized"):
            asyncio.run(_running_sandbox_without_share().extract_dropped_files())


class TestYaraScanOverTheSharedFolder:
    """``yara_scan`` reads real artifacts under the host side of the shared folder."""

    def test_a_scan_without_a_share_is_refused(self) -> None:
        """A sandbox with no shared folder cannot be scanned."""
        with pytest.raises(SandboxError, match="Shared folder not initialized"):
            asyncio.run(_HostBoundSandbox().yara_scan())

    def test_a_rules_file_replaces_the_built_in_rules(self, tmp_path: Path) -> None:
        """Rules read from ``rules_path`` decide the matches, not the built-in set.

        Args:
            tmp_path: Pytest temporary directory.
        """
        share = _share_with_output(tmp_path)
        sandbox = _HostBoundSandbox()
        sandbox.bind(share, running=True)
        artifact = share / "output" / "collected.bin"
        artifact.write_bytes(_INJECTOR_STRINGS + _CUSTOM_RULE_MARKER)
        rules = tmp_path / "custom.yar"
        rules.write_text(_CUSTOM_RULES, encoding="utf-8")

        matches = asyncio.run(sandbox.yara_scan(rules_path=str(rules)))

        assert {match["rule"] for match in matches} == {"CustomMarker"}
        assert {match["source"] for match in matches} == {str(artifact)}

    def test_dropped_file_archives_are_unpacked_and_their_members_scanned(self, tmp_path: Path) -> None:
        """Every ``dropped_files_*.zip`` is extracted and its files are the scan inputs.

        Args:
            tmp_path: Pytest temporary directory.
        """
        share = _share_with_output(tmp_path)
        output_dir = share / "output"
        sandbox = _HostBoundSandbox()
        sandbox.bind(share, running=True)
        for archive_name, member_name in (("dropped_files_aa.zip", "first.bin"), ("dropped_files_bb.zip", "second.bin")):
            with zipfile.ZipFile(output_dir / archive_name, "w") as archive:
                archive.writestr(f"Downloads/{member_name}", _INJECTOR_STRINGS)

        matches = asyncio.run(sandbox.yara_scan())

        sources = [Path(match["source"]) for match in matches]
        assert {match["rule"] for match in matches} == {"SuspiciousStrings"}
        assert sorted(source.name for source in sources) == ["first.bin", "second.bin"]
        for source in sources:
            extraction_dir = source.parent.parent
            assert extraction_dir.parent == output_dir
            assert extraction_dir.name.startswith("yara_scan_")
            assert source.parent.name == "Downloads"


class TestDispatcherResultReader:
    """``_read_dispatcher_result`` turns the guest's ticket files into a result."""

    def test_a_ticket_without_a_result_file_is_still_pending(self, tmp_path: Path) -> None:
        """A result file that cannot be read yields ``None`` so the caller keeps polling.

        Args:
            tmp_path: Pytest temporary directory.
        """
        paths = _make_dispatcher_paths(
            tmp_path / "t.cmd",
            tmp_path / "t.out.txt",
            tmp_path / "t.err.txt",
            tmp_path / "t.result.txt",
        )

        assert asyncio.run(_read_dispatcher_result(paths)) is None

    def test_a_result_without_output_files_has_empty_streams(self, tmp_path: Path) -> None:
        """When the guest wrote only an exit code, stdout and stderr come back empty.

        Args:
            tmp_path: Pytest temporary directory.
        """
        result_file = tmp_path / "t.result.txt"
        result_file.write_text("7", encoding="utf-8")
        paths = _make_dispatcher_paths(
            tmp_path / "t.cmd",
            tmp_path / "t.out.txt",
            tmp_path / "t.err.txt",
            result_file,
        )

        assert asyncio.run(_read_dispatcher_result(paths)) == (7, "", "")


class TestWinHandleFromFile:
    """``_win_handle_from_file`` returns the OS handle behind a Python file object."""

    def test_an_open_file_yields_its_os_handle(self, tmp_path: Path) -> None:
        """The handle equals the C runtime's own answer for the same descriptor.

        Args:
            tmp_path: Pytest temporary directory.
        """
        with (tmp_path / "handle.bin").open("wb") as stream:
            handle = _win_handle_from_file(stream)
            expected = msvcrt.get_osfhandle(stream.fileno())

        assert handle is not None
        assert handle == expected

    def test_a_closed_file_yields_none(self, tmp_path: Path) -> None:
        """A closed file has no descriptor, so no handle is reported.

        Args:
            tmp_path: Pytest temporary directory.
        """
        stream = (tmp_path / "closed.bin").open("wb")
        stream.close()

        assert _win_handle_from_file(stream) is None


class TestHostSideMinidump:
    """The host-side minidump helpers dump a real process, or report why they could not."""

    @pytest.mark.spawns_process
    def test_a_running_child_is_dumped_through_dbghelp(self, tmp_path: Path, idle_child: subprocess.Popen[str]) -> None:
        """A full-memory minidump of a live process is written and starts with the MDMP signature.

        Args:
            tmp_path: Pytest temporary directory.
            idle_child: A running child process to dump.
        """
        dump_path = tmp_path / "dumps" / "child.dmp"

        outcome = _minidump_via_dbghelp(idle_child.pid, dump_path)

        assert outcome == (True, "")
        with dump_path.open("rb") as written:
            assert written.read(len(_MINIDUMP_SIGNATURE)) == _MINIDUMP_SIGNATURE

    @pytest.mark.spawns_process
    def test_the_wrapper_reports_success_when_dbghelp_wrote_the_dump(
        self,
        tmp_path: Path,
        idle_child: subprocess.Popen[str],
    ) -> None:
        """The wrapper returns True once the dbghelp dump exists, without needing procdump.

        Args:
            tmp_path: Pytest temporary directory.
            idle_child: A running child process to dump.
        """
        dump_path = tmp_path / "wrapped.dmp"

        produced = asyncio.run(_HostBoundSandbox().minidump(idle_child.pid, dump_path))

        assert produced is True
        assert dump_path.stat().st_size > 0

    def test_a_process_that_cannot_be_opened_is_reported_with_the_open_failure(self, tmp_path: Path) -> None:
        """A pid that names no process fails at ``OpenProcess`` and creates no file.

        Args:
            tmp_path: Pytest temporary directory.
        """
        dump_path = tmp_path / "nothing.dmp"

        produced, reason = _minidump_via_dbghelp(_NONEXISTENT_PID, dump_path)

        assert produced is False
        assert reason.startswith("open_process_failed:")
        assert not dump_path.exists()

    @pytest.mark.spawns_process
    def test_a_dump_path_that_cannot_be_opened_for_writing_is_reported(
        self,
        tmp_path: Path,
        idle_child: subprocess.Popen[str],
    ) -> None:
        """A directory in place of the dump file fails the open and is reported as such.

        Args:
            tmp_path: Pytest temporary directory.
            idle_child: A running child process whose handle opens normally.
        """
        occupied = tmp_path / "occupied"
        occupied.mkdir()

        produced, reason = _minidump_via_dbghelp(idle_child.pid, occupied)

        assert produced is False
        assert reason.startswith("dump_open_failed:")

    def test_without_dbghelp_success_or_procdump_the_wrapper_reports_failure(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """With no procdump on ``PATH`` a failed dbghelp dump leaves the wrapper returning False.

        Args:
            tmp_path: Pytest temporary directory.
            monkeypatch: Pytest monkeypatch fixture, used to empty ``PATH``.
        """
        empty_bin = tmp_path / "empty_bin"
        empty_bin.mkdir()
        monkeypatch.setenv("PATH", str(empty_bin))
        dump_path = tmp_path / "never.dmp"

        produced = asyncio.run(_HostBoundSandbox().minidump(_NONEXISTENT_PID, dump_path))

        assert produced is False
        assert not dump_path.exists()


class TestGuestCommandsWithoutGuestTools:
    """Commands the sandbox sends fail cleanly when the guest lacks the tools they need."""

    @pytest.mark.spawns_process
    def test_a_screenshot_the_guest_cannot_take_raises_and_leaves_no_image(self, guest_without_tools: _HostBoundSandbox) -> None:
        """A failing capture command surfaces as ``SandboxError`` and no PNG appears.

        Args:
            guest_without_tools: A running sandbox whose guest cannot find ``powershell``.
        """
        with pytest.raises(SandboxError, match="Screenshot capture failed"):
            asyncio.run(guest_without_tools.capture_screenshot())

        assert not list((guest_without_tools.shared_folder() / "output").glob("screenshot_*.png"))

    @pytest.mark.spawns_process
    def test_a_failed_wmi_identity_query_is_reported_as_failed_verification(self, guest_without_tools: _HostBoundSandbox) -> None:
        """A non-zero exit from the verification query raises the verification error.

        Args:
            guest_without_tools: A running sandbox whose guest cannot find ``powershell``.
        """
        with pytest.raises(SandboxError, match="WMI hijack verification did not return spoofed values"):
            asyncio.run(guest_without_tools.query_wmi_identity())

    @pytest.mark.spawns_process
    def test_a_guest_without_xcopy_still_yields_an_archive_of_what_was_staged(self, guest_without_tools: _HostBoundSandbox) -> None:
        """Files found in the staging directory end up in the archive and the staging directory is removed.

        Args:
            guest_without_tools: A running sandbox whose guest cannot find ``xcopy``.
        """
        output_dir = guest_without_tools.shared_folder() / "output"
        payload = b"dropped-by-the-sample"

        async def scenario() -> tuple[Path, Path]:
            """Run the extraction while a file appears in its staging directory.

            Returns:
                tuple[Path, Path]: The archive path and the staging directory.
            """
            archive_path, staging_dir = await asyncio.gather(
                guest_without_tools.extract_dropped_files(),
                _drop_file_into_staging(output_dir, "payload.bin", payload),
            )
            return archive_path, staging_dir

        archive_path, staging_dir = asyncio.run(scenario())

        assert archive_path.parent == output_dir
        assert archive_path.name.startswith("dropped_files_")
        assert archive_path.suffix == ".zip"
        with zipfile.ZipFile(archive_path) as archive:
            assert archive.namelist() == ["Downloads/payload.bin"]
            assert archive.read("Downloads/payload.bin") == payload
        assert not staging_dir.exists()

    @pytest.mark.spawns_process
    def test_the_archive_is_copied_to_the_requested_output_path(self, guest_without_tools: _HostBoundSandbox, tmp_path: Path) -> None:
        """An ``output_path`` receives a copy of the archive and its parents are created.

        Args:
            guest_without_tools: A running sandbox whose guest cannot find ``xcopy``.
            tmp_path: Pytest temporary directory.
        """
        destination = tmp_path / "exported" / "nested" / "dropped.zip"

        returned = asyncio.run(guest_without_tools.extract_dropped_files(destination))

        assert returned == destination
        with zipfile.ZipFile(destination) as archive:
            assert archive.namelist() == []
        assert len(list((guest_without_tools.shared_folder() / "output").glob("dropped_files_*.zip"))) == 1


class TestGuestCommandsWithHostTools:
    """Commands the sandbox sends run for real when the guest has the host's tools."""

    @pytest.mark.spawns_process
    def test_an_unreadable_first_source_directory_aborts_the_extraction(self, guest_with_host_tools: _HostBoundSandbox) -> None:
        """The guest user's Downloads directory does not exist here, so xcopy fails to initialize.

        Args:
            guest_with_host_tools: A running sandbox whose guest has the host ``PATH``.
        """
        with pytest.raises(SandboxError, match="Dropped file extraction failed"):
            asyncio.run(guest_with_host_tools.extract_dropped_files())


def _drop_file_if_staged(output_dir: Path, file_name: str, payload: bytes) -> Path | None:
    """Write a file into the extraction staging directory if it exists yet.

    Args:
        output_dir: The shared folder's ``output`` directory.
        file_name: Name of the file to create under a ``Downloads`` subfolder.
        payload: Bytes to write.

    Returns:
        Path | None: The staging directory written into, or None when none exists yet.
    """
    staging = [entry for entry in output_dir.glob("dropped_*") if entry.is_dir()]
    if not staging:
        return None
    target_dir = staging[0] / "Downloads"
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / file_name).write_bytes(payload)
    return staging[0]


async def _drop_file_into_staging(output_dir: Path, file_name: str, payload: bytes) -> Path:
    """Write a file into the extraction staging directory as soon as it appears.

    Args:
        output_dir: The shared folder's ``output`` directory.
        file_name: Name of the file to create under a ``Downloads`` subfolder.
        payload: Bytes to write.

    Returns:
        Path: The staging directory the file was written into.

    Raises:
        AssertionError: If no staging directory appears in time.
    """
    deadline = time.monotonic() + _STAGING_WAIT_SECONDS
    while time.monotonic() < deadline:
        staged = await asyncio.to_thread(_drop_file_if_staged, output_dir, file_name, payload)
        if staged is not None:
            return staged
        await asyncio.sleep(_STAGING_POLL_SECONDS)
    message = "the extraction never created a staging directory"
    raise AssertionError(message)
