# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Zachary Flint
#
# This file is part of Intellicrack. See LICENSE for details.
r"""Gate for S18-D07: the guest agent's command channel must answer promptly.

The in-guest agent generated by
:meth:`QEMUSandbox._windows_agent_script_content` is the only way the host
reaches a Windows guest, and :meth:`QEMUSandbox.start` fails outright if the
production :class:`GuestAgentClient` cannot complete its readiness handshake
within the connect budget. S18-D07 is that the agent served that channel from
the same loop as its telemetry sweep: it checked for a pending connection once
per pass, accepted exactly one, and then spent the rest of the pass enumerating
the process table and both socket tables before sleeping a second - all of it
downstream of eight process launches and a recursive ``FileSystemWatcher`` over
the whole system drive, whose event actions then compete for that runspace for
as long as the agent runs.

Measured against the real ``windows11-intellicrack-v4-clean`` guest under WHPX,
one ping took 19s to come back, and three earlier attempts with a 30s budget
each got no answer at all - while ``Get-NetTCPConnection`` inside that guest
showed ``0.0.0.0:4445`` listening the entire time. Every one of those abandoned
attempts also left a socket queued ahead of the next, so the agent fell further
behind the harder the host tried. The sandbox reported ``guest agent failed to
connect``, which reads like a guest that never booted.

The two properties gated here are the ones that failure was made of, and both
are measured against the real generated script running under a real
``powershell.exe``, not a model of it:

* Connections the host gave up on must not delay the next one. The host makes
  an attempt every two seconds while it waits, so by the time the agent is up
  there are already several abandoned sockets, and draining them one per pass
  is what turned a slow start into a failed one.
* One connection must not be able to lock the channel. The agent used to read
  from its first client until that client closed, so a peer that connected and
  went quiet - exactly what a host whose handshake timed out leaves behind when
  the reset is lost - denied the channel to every later connection forever.

The agent is written to a monitor directory holding nothing else, so its
launcher loop starts no monitors: which files sit beside the agent is a
property of the guest, not of the channel, and eight live ETW monitors would
tell these gates nothing. That the channel is nonetheless opened before that
loop and before the watcher is gated separately, on the generated text.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import re
import time
from typing import TYPE_CHECKING, Any, Final, cast

import pytest
import pytest_asyncio

from intellicrack.sandbox.qemu import GuestAgentClient, QEMUSandbox
from tests.sandbox.qemu.generated_agent_peer import (
    AGENT_SCRIPT_NAME,
    LISTENER_LINE,
    MONITOR_DIRECTORY,
    POWERSHELL,
    script_line,
)


if TYPE_CHECKING:
    from collections.abc import AsyncGenerator
    from pathlib import Path

_HOST: Final[str] = "127.0.0.1"

_LISTENER_PORT: Final = re.compile(r",\s*(?P<port>\d+)\s*\)")

_READY_TIME_LIMIT: Final[float] = 90.0
"""Total seconds the agent is given to reach its first answered ping."""

_READY_ATTEMPT_LIMIT: Final[float] = 5.0
_READY_ATTEMPT_GAP: Final[float] = 0.5

_ABANDONED_CONNECTIONS: Final[int] = 15
"""How many attempts the host is modelled as having given up on.

The production client retries every
:data:`intellicrack.sandbox.qemu._AGENT_CONNECT_BACKOFF_INTERVAL` seconds for
the whole connect budget, so this is the low end of what a real slow start
leaves behind.
"""

_PROMPT_TIME_LIMIT: Final[float] = 6.0
"""Seconds a handshake may take once the agent is known to be up.

Comfortably above the tens of milliseconds an idle channel answers in, and
comfortably below the one second per abandoned connection that draining them in
the telemetry loop costs.
"""

_LOCKOUT_TIME_LIMIT: Final[float] = 20.0
"""Seconds a second client may take while a first one is connected and silent."""

_ACCEPT_SETTLE: Final[float] = 1.5
"""Seconds allowed for the agent to accept a connection before the next opens."""

_COMMAND_TIME_LIMIT: Final[float] = 60.0
_COMMAND_TIMEOUT_FIELD: Final[int] = 30

_ECHO_MARKER: Final[str] = "s18d07-channel-alive"
_SHELL: Final[str] = "cmd.exe"

_RESULT_MESSAGE_TYPE: Final[str] = "result"
_MESSAGE_TYPE_FIELD: Final[str] = "type"
_MESSAGE_DATA_FIELD: Final[str] = "data"
_EXIT_CODE_FIELD: Final[str] = "exit_code"
_STDOUT_FIELD: Final[str] = "stdout"

_MONITOR_LAUNCH: Final[str] = "Start-Process"
_WATCHER_REGISTRATION: Final[str] = "Register-ObjectEvent"
_LISTENER_START: Final[str] = "$listener.Start()"

_ERR_NO_PORT: Final[str] = "the generated agent's listener statement names no port: {line!r}"
_ERR_NEVER_READY: Final[str] = "the generated agent answered no ping on port {port} within {budget}s"


class _AgentScriptSource(QEMUSandbox):
    """Exposes the in-guest agent source the production sandbox generates.

    The generator is protected, and reading it off the class from outside would
    need a suppression. A subclass reads its own inherited member instead, which
    is the same source the sandbox writes into the share.
    """

    @classmethod
    def agent_script(cls) -> str:
        """Return the generated Windows agent script.

        Returns:
            str: Full text of the ``agent.ps1`` the sandbox writes.
        """
        return cls._windows_agent_script_content()


def _request(payload: dict[str, object]) -> bytes:
    """Frame one agent request the way the production client frames it.

    Args:
        payload: Request body.

    Returns:
        bytes: The newline-terminated JSON the agent reads.
    """
    return (json.dumps(payload) + "\n").encode()


def _agent_port(agent_script: str) -> int:
    """Read the port the generated agent binds out of its own listener statement.

    Args:
        agent_script: Full text of the generated ``agent.ps1``.

    Returns:
        int: The port the guest agent listens on.

    Raises:
        AssertionError: If the listener statement names no port.
    """
    line = script_line(agent_script, LISTENER_LINE)
    matched = _LISTENER_PORT.search(line)
    if matched is None:
        raise AssertionError(_ERR_NO_PORT.format(line=line))
    return int(matched["port"])


async def _read_message(reader: asyncio.StreamReader, wanted: str, deadline: float) -> dict[str, Any] | None:
    """Read agent lines until one of the wanted type arrives or time runs out.

    Args:
        reader: Stream reader for the open agent socket.
        wanted: Value of the message's ``type`` member to wait for.
        deadline: Monotonic clock reading the wait must end by.

    Returns:
        dict[str, Any] | None: The parsed message, or None if the agent closed
        the channel or never sent one.
    """
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return None
        try:
            line = await asyncio.wait_for(reader.readline(), timeout=remaining)
        except (TimeoutError, OSError):
            return None
        if not line:
            return None
        try:
            parsed: object = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(parsed, dict):
            continue
        message = cast("dict[str, Any]", parsed)
        if message.get(_MESSAGE_TYPE_FIELD) == wanted:
            return message


async def _close(writer: asyncio.StreamWriter) -> None:
    """Close one agent socket, however the peer left it.

    Args:
        writer: Stream writer to close.
    """
    writer.close()
    with contextlib.suppress(OSError):
        await writer.wait_closed()


async def _handshake(port: int, time_limit: float) -> float | None:
    """Open a channel, ping the agent, and time its reply.

    Args:
        port: Port the agent listens on.
        time_limit: Seconds allowed for the connect and the reply together.

    Returns:
        float | None: Seconds the handshake took, or None if the agent did not
        answer within the budget.
    """
    started = time.monotonic()
    try:
        reader, writer = await asyncio.wait_for(asyncio.open_connection(_HOST, port), timeout=time_limit)
    except (TimeoutError, OSError):
        return None
    try:
        writer.write(_request({_MESSAGE_TYPE_FIELD: GuestAgentClient.PING_REQUEST_TYPE}))
        await writer.drain()
        reply = await _read_message(reader, GuestAgentClient.PONG_MESSAGE_TYPE, started + time_limit)
    except OSError:
        return None
    finally:
        await _close(writer)
    return None if reply is None else time.monotonic() - started


async def _await_ready(port: int) -> float:
    """Wait for the agent to answer its first ping.

    Args:
        port: Port the agent listens on.

    Returns:
        float: Seconds from the first attempt to the answered one.

    Raises:
        AssertionError: If the agent never answers within
            :data:`_READY_TIME_LIMIT`.
    """
    started = time.monotonic()
    while time.monotonic() - started < _READY_TIME_LIMIT:
        if await _handshake(port, _READY_ATTEMPT_LIMIT) is not None:
            return time.monotonic() - started
        await asyncio.sleep(_READY_ATTEMPT_GAP)
    unanswered = _ERR_NEVER_READY.format(port=port, budget=_READY_TIME_LIMIT)
    raise AssertionError(unanswered)


class _RunningAgent:
    """The generated Windows guest agent, running as a real ``powershell.exe``.

    Attributes:
        port: Port the agent's own listener statement binds.
    """

    port: int

    def __init__(self, process: asyncio.subprocess.Process, port: int) -> None:
        """Hold a launched agent process.

        Args:
            process: The running ``powershell.exe``.
            port: Port the agent listens on.
        """
        self._process = process
        self.port = port

    async def stop(self) -> None:
        """Kill the agent, which otherwise runs forever."""
        if self._process.returncode is None:
            self._process.kill()
        await self._process.communicate()


@pytest_asyncio.fixture
async def agent(tmp_path: Path) -> AsyncGenerator[_RunningAgent]:
    """Run the production-generated guest agent and wait for it to answer.

    Args:
        tmp_path: Directory the share standing in for the guest's is built
            under.

    Yields:
        _RunningAgent: The running agent, already proven to answer a ping.
    """
    monitor = tmp_path / "shared" / MONITOR_DIRECTORY
    monitor.mkdir(parents=True)
    script = _AgentScriptSource.agent_script()
    agent_path = monitor / AGENT_SCRIPT_NAME
    await asyncio.to_thread(agent_path.write_text, script, encoding="utf-8")

    process = await asyncio.create_subprocess_exec(
        POWERSHELL,
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(agent_path),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    running = _RunningAgent(process, _agent_port(script))
    try:
        await _await_ready(running.port)
        yield running
    finally:
        await running.stop()


class TestAbandonedConnectionsDoNotDelayTheLiveOne:
    """What the host gave up on must not queue ahead of what it is waiting for."""

    @pytest.mark.asyncio
    async def test_a_handshake_behind_fifteen_dead_sockets_is_still_prompt(
        self,
        agent: _RunningAgent,
    ) -> None:
        """The agent must clear abandoned sockets without spending a pass each.

        Fifteen connections are opened and dropped, which is what a host that
        retried every two seconds through a slow guest start leaves behind.
        Accepting one per telemetry pass costs at least the pass's own second
        each, so the handshake that follows arrives far outside the budget the
        production client allows a single attempt.

        Args:
            agent: The running generated agent.
        """
        for _ in range(_ABANDONED_CONNECTIONS):
            _reader, writer = await asyncio.open_connection(_HOST, agent.port)
            await _close(writer)
        await asyncio.sleep(_ACCEPT_SETTLE)

        elapsed = await _handshake(agent.port, _PROMPT_TIME_LIMIT)

        assert elapsed is not None, (
            f"the agent answered no ping within {_PROMPT_TIME_LIMIT}s behind {_ABANDONED_CONNECTIONS} abandoned connections"
        )

    @pytest.mark.asyncio
    async def test_repeated_handshakes_stay_prompt(self, agent: _RunningAgent) -> None:
        """Each attempt the host makes must be answered, not just the last one.

        The production client hands every attempt the same budget, so an agent
        that answers only after several have been abandoned still fails the
        start it was supposed to complete.

        Args:
            agent: The running generated agent.
        """
        for attempt in range(3):
            elapsed = await _handshake(agent.port, _PROMPT_TIME_LIMIT)
            assert elapsed is not None, f"handshake {attempt} went unanswered within {_PROMPT_TIME_LIMIT}s"


class TestOneClientCannotLockTheChannel:
    """A peer that connects and says nothing must not deny the channel."""

    @pytest.mark.asyncio
    async def test_a_silent_client_does_not_shut_out_the_next_one(
        self,
        agent: _RunningAgent,
    ) -> None:
        """A connection held open and idle must not block a later handshake.

        This is exactly what the host leaves behind when its handshake budget
        expires and the reset never reaches the guest. Reading from the first
        client until it closes hands that peer the whole channel for as long as
        it stays connected, so the host can never reconnect.

        Args:
            agent: The running generated agent.
        """
        _idle_reader, idle_writer = await asyncio.open_connection(_HOST, agent.port)
        try:
            await asyncio.sleep(_ACCEPT_SETTLE)

            elapsed = await _handshake(agent.port, _LOCKOUT_TIME_LIMIT)

            assert elapsed is not None, f"a second client got no answer within {_LOCKOUT_TIME_LIMIT}s while a silent one was connected"
        finally:
            await _close(idle_writer)


class TestTheChannelStillRunsCommands:
    """Moving the channel off the telemetry loop must not change what it does."""

    @pytest.mark.asyncio
    async def test_a_dispatched_command_runs_and_its_output_comes_back(
        self,
        agent: _RunningAgent,
    ) -> None:
        """An ``execute`` request must still run a real child and report it.

        The channel is served from a runspace of its own, so everything the
        request handler needs - the allowlist, the argument rendering, the JSON
        framing - has to be reachable there. A runspace built without them
        answers nothing at all, which no amount of handshaking would reveal.

        Args:
            agent: The running generated agent.
        """
        reader, writer = await asyncio.open_connection(_HOST, agent.port)
        try:
            writer.write(
                _request(
                    {
                        _MESSAGE_TYPE_FIELD: "execute",
                        "command": _SHELL,
                        "args": ["/c", "echo", _ECHO_MARKER],
                        "timeout": _COMMAND_TIMEOUT_FIELD,
                    },
                ),
            )
            await writer.drain()
            reply = await _read_message(reader, _RESULT_MESSAGE_TYPE, time.monotonic() + _COMMAND_TIME_LIMIT)
        finally:
            await _close(writer)

        assert reply is not None, f"the agent ran no command within {_COMMAND_TIME_LIMIT}s"
        data: object = reply.get(_MESSAGE_DATA_FIELD)
        assert isinstance(data, dict), f"the result carried no data member: {reply!r}"
        payload = cast("dict[str, Any]", data)
        assert payload.get(_EXIT_CODE_FIELD) == 0, f"the guest could not run the command: {payload!r}"
        assert _ECHO_MARKER in str(payload.get(_STDOUT_FIELD, "")), f"what the command wrote never came back: {payload!r}"


class TestTheChannelOpensBeforeTheSlowWork:
    """The listener must not sit behind the agent's own bring-up."""

    def test_the_listener_starts_before_the_monitors_and_the_watcher(self) -> None:
        """``$listener.Start()`` must precede both slow stages of the script.

        The monitor loop launches eight processes and the watcher registration
        arms a recursive ``FileSystemWatcher`` over the whole system drive.
        Both run before the agent would otherwise be reachable, and the host
        starts connecting the moment its launcher is invoked, so every second
        either one spends is a second of the connect budget spent refusing
        connections.
        """
        script = _AgentScriptSource.agent_script()

        listener_at = script.index(_LISTENER_START)
        monitors_at = script.index(_MONITOR_LAUNCH)
        watcher_at = script.index(_WATCHER_REGISTRATION)

        assert listener_at < monitors_at, "the agent launches its monitors before it starts listening"
        assert listener_at < watcher_at, "the agent arms its filesystem watcher before it starts listening"
