class OpenBase:
    use_cache: bool
    cache: dict[str, str]
    asyn: bool
    def __init__(self, filename: str = ..., flags: list[str] = ...) -> None: ...
    def invalidate_cache(self) -> None: ...
    def quit(self) -> None: ...
    def cmd(self, cmd: str, **kwargs: object) -> str | None: ...
    def cmdj(self, cmd: str, **kwargs: object) -> object: ...
    def cmdJ(self, cmd: str, **kwargs: object) -> object | None: ...
    def cmd2(self, cmd: str, **kwargs: object) -> object: ...
    def cmd2j(self, cmd: str, **kwargs: object) -> object: ...
    def call(self, cmd: str, **kwargs: object) -> str | None: ...
    def syscmd(self, cmd: str) -> bytes: ...
    def syscmdj(self, cmd: str) -> object | None: ...
    def set_timeout(self, timeout: float) -> None: ...
