import asyncio
from collections.abc import Coroutine

def run_bridge_coroutine[T](coro: Coroutine[object, object, T]) -> T | None: ...
def _log_task_exception(task: asyncio.Task[object]) -> None: ...
