from collections.abc import Callable
from typing import Any

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QPlainTextEdit,
    QTableWidget,
    QTableWidgetItem,
    QTreeWidget,
    QTreeWidgetItem,
)

def _resolve(obj: object, method_name: str) -> Callable[..., Any]: ...
def set_sorting_enabled(table: QTableWidget, enable: bool) -> None: ...
def set_header_labels(tree: QTreeWidget, labels: list[str]) -> None: ...
def set_max_block_count(editor: QPlainTextEdit, maximum: int) -> None: ...
def edit_table_item(table: QTableWidget, item: QTableWidgetItem | None) -> None: ...
def get_current_tree_item(tree: QTreeWidget) -> QTreeWidgetItem | None: ...
def tree_item_set_data(item: QTreeWidgetItem, column: int, role: Qt.ItemDataRole, value: object) -> None: ...
def tree_item_data(item: QTreeWidgetItem, column: int, role: Qt.ItemDataRole) -> object: ...
