from typing import IO, Any, Sequence

class Image:
    format: str | None
    mode: str
    size: tuple[int, int]
    info: dict[str, Any]

    def save(self, fp: str | IO[bytes], format: str | None = None, **params: Any) -> None: ...
    def resize(self, size: tuple[int, int], resample: int = ..., **kwargs: Any) -> "Image": ...
    def crop(self, box: tuple[int, int, int, int] | None = None) -> "Image": ...
    def convert(self, mode: str | None = None, **kwargs: Any) -> "Image": ...
    def copy(self) -> "Image": ...
    def show(self, title: str | None = None) -> None: ...
    def tobytes(self, encoder_name: str = "raw", *args: Any) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def close(self) -> None: ...

def open(fp: str | IO[bytes], mode: str = "r", formats: Sequence[str] | None = None) -> Image: ...
def new(mode: str, size: tuple[int, int], color: int | tuple[int, ...] | str = 0) -> Image: ...
def fromarray(obj: Any, mode: str | None = None) -> Image: ...
def frombytes(mode: str, size: tuple[int, int], data: bytes, decoder_name: str = "raw", *args: Any) -> Image: ...
