; AUTO-GENERATED by packaging/stage.ps1 from src/intellicrack/_metadata.py.
; Do not edit by hand: packaging/intellicrack.iss #includes this file, and
; tests/packaging/test_version_consistency.py gates that every copy of the
; version across the repository agrees with pyproject.toml.
#define AppVersion "0.1.0a1"
#define AppVerNumeric "0.1.0.0"
